// Autogenerated!!! DO NOT MODIFY!
// Source: Elements.Core/Extensions/EasingExtensions.tt
// Generated on: 10/02/2024 16:17:48

namespace Elements.Core
{
    // Equations sourced from Robert Penner's original equations, adapted by Ryuvi
    // Source: http://robertpenner.com/easing/

    /*
    Disclaimer for Robert Penner's Easing Equations license:

    TERMS OF USE - EASING EQUATIONS

    Open source under the BSD License.

    Copyright © 2001 Robert Penner
    All rights reserved.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

        * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
        * Neither the name of the author nor the names of contributors may be used to endorse or promote products derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
        BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
        IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
        EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
        LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
        STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
        EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
    */

    public static partial class MathX
    {
        #region SINE
        public static float EaseInSineFloat(float time, float begin, float change, float duration) => -change * Cos(time / duration * (PI / 2f)) + change + begin;
        public static float EaseOutSineFloat(float time, float begin, float change, float duration) => change * Sin(time / duration * (PI / 2f)) + begin;
        public static float EaseInOutSineFloat(float time, float begin, float change, float duration) => -change / 2f * (Cos(PI * time / duration) -1f) + begin;
        public static double EaseInSineDouble(double time, double begin, double change, double duration) => -change * Cos(time / duration * (PI / 2f)) + change + begin;
        public static double EaseOutSineDouble(double time, double begin, double change, double duration) => change * Sin(time / duration * (PI / 2f)) + begin;
        public static double EaseInOutSineDouble(double time, double begin, double change, double duration) => -change / 2f * (Cos(PI * time / duration) -1f) + begin;
        #endregion

        #region QUADRADIC
        public static float EaseInQuadraticFloat(float time, float begin, float change, float duration)
        {
            time /= duration;
            return change * time * time + begin;
        }
        public static float EaseOutQuadraticFloat(float time, float begin, float change, float duration) => 1f - EaseInQuadraticFloat(1f - time, begin, change, duration);
        public static float EaseInOutQuadraticFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInQuadraticFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuadraticFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInQuadraticDouble(double time, double begin, double change, double duration)
        {
            time /= duration;
            return change * time * time + begin;
        }
        public static double EaseOutQuadraticDouble(double time, double begin, double change, double duration) => 1f - EaseInQuadraticDouble(1f - time, begin, change, duration);
        public static double EaseInOutQuadraticDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInQuadraticDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuadraticDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region CUBIC
        public static float EaseInCubicFloat(float time, float begin, float change, float duration)
        {
            time /= duration;
            return change * time * time * time + begin;
        }
        public static float EaseOutCubicFloat(float time, float begin, float change, float duration) => 1f - EaseInCubicFloat(1f - time, begin, change, duration);
        public static float EaseInOutCubicFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInCubicFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInCubicFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInCubicDouble(double time, double begin, double change, double duration)
        {
            time /= duration;
            return change * time * time * time + begin;
        }
        public static double EaseOutCubicDouble(double time, double begin, double change, double duration) => 1f - EaseInCubicDouble(1f - time, begin, change, duration);
        public static double EaseInOutCubicDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInCubicDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInCubicDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region QUARTIC
        public static float EaseInQuarticFloat(float time, float begin, float change, float duration)
        {
            time /= duration;
            return change * time * time * time * time + begin;
        }
        public static float EaseOutQuarticFloat(float time, float begin, float change, float duration) => 1f - EaseInQuarticFloat(1f - time, begin, change, duration);
        public static float EaseInOutQuarticFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInQuarticFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuarticFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInQuarticDouble(double time, double begin, double change, double duration)
        {
            time /= duration;
            return change * time * time * time * time + begin;
        }
        public static double EaseOutQuarticDouble(double time, double begin, double change, double duration) => 1f - EaseInQuarticDouble(1f - time, begin, change, duration);
        public static double EaseInOutQuarticDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInQuarticDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuarticDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region QUINTIC
        public static float EaseInQuinticFloat(float time, float begin, float change, float duration)
        {
            time /= duration;
            return change * time * time * time * time * time + begin;
        }
        public static float EaseOutQuinticFloat(float time, float begin, float change, float duration) => 1f - EaseInQuinticFloat(1f - time, begin, change, duration);
        public static float EaseInOutQuinticFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInQuinticFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuinticFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInQuinticDouble(double time, double begin, double change, double duration)
        {
            time /= duration;
            return change * time * time * time * time * time + begin;
        }
        public static double EaseOutQuinticDouble(double time, double begin, double change, double duration) => 1f - EaseInQuinticDouble(1f - time, begin, change, duration);
        public static double EaseInOutQuinticDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInQuinticDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInQuinticDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region EXPONENTIAL
        public static float EaseInExponentialFloat(float time, float begin, float change, float duration) => time == 0f ? begin : change * Pow(2f, 10f * (time / duration -1f)) + begin;
        public static float EaseOutExponentialFloat(float time, float begin, float change, float duration) => 1f - EaseInExponentialFloat(1f - time, begin, change, duration);
        public static float EaseInOutExponentialFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInExponentialFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInExponentialFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInExponentialDouble(double time, double begin, double change, double duration) => time == 0f ? begin : change * Pow(2f, 10f * (time / duration -1f)) + begin;
        public static double EaseOutExponentialDouble(double time, double begin, double change, double duration) => 1f - EaseInExponentialDouble(1f - time, begin, change, duration);
        public static double EaseInOutExponentialDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInExponentialDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInExponentialDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region CIRCULAR
        public static float EaseInCircularFloat(float time, float begin, float change, float duration)
        {
            time /= duration;
            return -change * (Sqrt(1f - time * time) - 1f) + begin;
        }
        public static float EaseOutCircularFloat(float time, float begin, float change, float duration) => 1f - EaseInCircularFloat(1f - time, begin, change, duration);
        public static float EaseInOutCircularFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                ? EaseInCircularFloat(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInCircularFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInCircularDouble(double time, double begin, double change, double duration)
        {
            time /= duration;
            return -change * (Sqrt(1f - time * time) - 1f) + begin;
        }
        public static double EaseOutCircularDouble(double time, double begin, double change, double duration) => 1f - EaseInCircularDouble(1f - time, begin, change, duration);
        public static double EaseInOutCircularDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                ? EaseInCircularDouble(time * 2f, begin, change, duration) / 2f
                : 1f - EaseInCircularDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion

        #region REBOUND
        public static float EaseInReboundFloat(float time, float begin, float change, float duration, float overshoot)
        {
            time /= duration;
            return change * time * time * ((overshoot + 1f) * time - overshoot) + begin;
        }
        public static float EaseOutReboundFloat(float time, float begin, float change, float duration, float overshoot) => 1f - EaseInReboundFloat(1f - time, begin, change, duration, overshoot);
        public static float EaseInOutReboundFloat(float time, float begin, float change, float duration, float overshoot)
        {
            return time < 0.5f
                ? EaseInReboundFloat(time * 2f, begin, change, duration, overshoot) / 2f
                : 1f - EaseInReboundFloat((1f - time) * 2f, begin, change, duration, overshoot) / 2f;
        }
        public static double EaseInReboundDouble(double time, double begin, double change, double duration, double overshoot)
        {
            time /= duration;
            return change * time * time * ((overshoot + 1f) * time - overshoot) + begin;
        }
        public static double EaseOutReboundDouble(double time, double begin, double change, double duration, double overshoot) => 1f - EaseInReboundDouble(1f - time, begin, change, duration, overshoot);
        public static double EaseInOutReboundDouble(double time, double begin, double change, double duration, double overshoot)
        {
            return time < 0.5f
                ? EaseInReboundDouble(time * 2f, begin, change, duration, overshoot) / 2f
                : 1f - EaseInReboundDouble((1f - time) * 2f, begin, change, duration, overshoot) / 2f;
        }
        #endregion

        #region ELASTIC
        public static float EaseInElasticFloat(float time, float begin, float change, float duration, float amplitude, float period) => 1f - EaseOutElasticFloat(1f - time, begin, change, duration, amplitude, period);

        public static float EaseOutElasticFloat(float time, float begin, float change, float duration, float amplitude, float period)
        {
            float s;

            if (time == 0f)
                return begin;

            time = time /= duration;

            if (time == 1f)
                return begin + change;

            if (period == 0f)
                period = duration * 0.3f;

            if (amplitude == 0f || amplitude < Abs(change))
            {
                amplitude = change;
                s = period / 4f;
            }
            else
                s = period / (2f * PI) * Asin(change / amplitude);

            return (amplitude * Pow(2f, -10f * time) * Sin((time * duration - s) * (2f * PI) / period)) + change + begin;
        }

        public static float EaseInOutElasticFloat(float time, float begin, float change, float duration, float amplitude, float period)
        {
            return time < 0.5f
                ? EaseInElasticFloat(time * 2f, begin, change, duration, amplitude, period) / 2f
                : 1f - EaseInElasticFloat((1f - time) * 2f, begin, change, duration, amplitude, period) / 2f;
        }
        public static double EaseInElasticDouble(double time, double begin, double change, double duration, double amplitude, double period) => 1f - EaseOutElasticDouble(1f - time, begin, change, duration, amplitude, period);

        public static double EaseOutElasticDouble(double time, double begin, double change, double duration, double amplitude, double period)
        {
            double s;

            if (time == 0f)
                return begin;

            time = time /= duration;

            if (time == 1f)
                return begin + change;

            if (period == 0f)
                period = duration * 0.3f;

            if (amplitude == 0f || amplitude < Abs(change))
            {
                amplitude = change;
                s = period / 4f;
            }
            else
                s = period / (2f * PI) * Asin(change / amplitude);

            return (amplitude * Pow(2f, -10f * time) * Sin((time * duration - s) * (2f * PI) / period)) + change + begin;
        }

        public static double EaseInOutElasticDouble(double time, double begin, double change, double duration, double amplitude, double period)
        {
            return time < 0.5f
                ? EaseInElasticDouble(time * 2f, begin, change, duration, amplitude, period) / 2f
                : 1f - EaseInElasticDouble((1f - time) * 2f, begin, change, duration, amplitude, period) / 2f;
        }
        #endregion

        #region BOUNCE
        public static float EaseInBounceFloat(float time, float begin, float change, float duration) => 1f - EaseOutBounceFloat(1f - time, begin, change, duration);

        public static float EaseOutBounceFloat(float time, float begin, float change, float duration)
        {
            float divisor = 2.75f;
            float magnitude = 7.5625f;

            time /= duration;

            if (time < 1f / divisor)
            {
                return change * (magnitude * time * time) + begin;
            }
            else if (time < 2f / divisor)
            {
                time -= 1.5f / divisor;
                return change * (magnitude * time * time + 0.75f) + begin;
            }
            else if (time < 2.5f / divisor)
            {
                time -= 2.25f / divisor;
                return change * (magnitude * time * time + 0.9375f) + begin;
            }
            else
            {
                time -= 2.625f / divisor;
                return change * (magnitude * time * time + 0.984375f) + begin;
            }
        }

        public static float EaseInOutBounceFloat(float time, float begin, float change, float duration)
        {
            return time < 0.5f
                 ? EaseInBounceFloat(time * 2f, begin, change, duration) / 2f
                 : 1f - EaseInBounceFloat((1f - time) * 2f, begin, change, duration) / 2f;
        }
        public static double EaseInBounceDouble(double time, double begin, double change, double duration) => 1f - EaseOutBounceDouble(1f - time, begin, change, duration);

        public static double EaseOutBounceDouble(double time, double begin, double change, double duration)
        {
            double divisor = 2.75f;
            double magnitude = 7.5625f;

            time /= duration;

            if (time < 1f / divisor)
            {
                return change * (magnitude * time * time) + begin;
            }
            else if (time < 2f / divisor)
            {
                time -= 1.5f / divisor;
                return change * (magnitude * time * time + 0.75f) + begin;
            }
            else if (time < 2.5f / divisor)
            {
                time -= 2.25f / divisor;
                return change * (magnitude * time * time + 0.9375f) + begin;
            }
            else
            {
                time -= 2.625f / divisor;
                return change * (magnitude * time * time + 0.984375f) + begin;
            }
        }

        public static double EaseInOutBounceDouble(double time, double begin, double change, double duration)
        {
            return time < 0.5f
                 ? EaseInBounceDouble(time * 2f, begin, change, duration) / 2f
                 : 1f - EaseInBounceDouble((1f - time) * 2f, begin, change, duration) / 2f;
        }
        #endregion
    }
}
