// Autogenerated!!! DO NOT MODIFY!
// Generated on: 02/27/2024 20:16:16
// This was created because the rules for dividing numbers can get quite complicated. For example https://stackoverflow.com/a/26595091/2095344

using System;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Elements.Core
{
    
    public static partial class MathX
    {


        public static bool CanDivideBy(uint divisor)
        {
            return divisor != 0;
        }

        public static bool CanDivide(uint dividend, uint divisor)
        {
            
            return divisor != 0;
        }

        // Dividing uint2 by uint2
        public static bool CanDivide(in uint2 dividend, in uint2 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y);
            
        }

        // Dividing uint2 by uint
        public static bool CanDivide(in uint2 dividend, uint divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor);
            
        }

        // Dividing uint by uint2
        public static bool CanDivide(uint dividend, in uint2 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y);
            
        }

        public static bool CanDivideBy(in uint2 divisor)
        {
            return divisor.x != 0 && divisor.y != 0;
            
        }

        // Dividing uint3 by uint3
        public static bool CanDivide(in uint3 dividend, in uint3 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z) ;
            
        }

        // Dividing uint3 by uint
        public static bool CanDivide(in uint3 dividend, uint divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor);
            
        }

        // Dividing uint by uint3
        public static bool CanDivide(uint dividend, in uint3 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z);
            
        }

        public static bool CanDivideBy(in uint3 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0;
            
        }

        // Dividing uint4 by uint4
        public static bool CanDivide(in uint4 dividend, in uint4 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z)  && MathX.CanDivide(dividend.w, divisor.w) ;
            
        }

        // Dividing uint4 by uint
        public static bool CanDivide(in uint4 dividend, uint divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor) && MathX.CanDivide(dividend.w, divisor);
            
        }

        // Dividing uint by uint4
        public static bool CanDivide(uint dividend, in uint4 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z) && MathX.CanDivide(dividend, divisor.w);
            
        }

        public static bool CanDivideBy(in uint4 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0 && divisor.w != 0;
            
        }




        public static bool CanDivideBy(ulong divisor)
        {
            return divisor != 0;
        }

        public static bool CanDivide(ulong dividend, ulong divisor)
        {
            
            return divisor != 0;
        }

        // Dividing ulong2 by ulong2
        public static bool CanDivide(in ulong2 dividend, in ulong2 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y);
            
        }

        // Dividing ulong2 by ulong
        public static bool CanDivide(in ulong2 dividend, ulong divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor);
            
        }

        // Dividing ulong by ulong2
        public static bool CanDivide(ulong dividend, in ulong2 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y);
            
        }

        public static bool CanDivideBy(in ulong2 divisor)
        {
            return divisor.x != 0 && divisor.y != 0;
            
        }

        // Dividing ulong3 by ulong3
        public static bool CanDivide(in ulong3 dividend, in ulong3 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z) ;
            
        }

        // Dividing ulong3 by ulong
        public static bool CanDivide(in ulong3 dividend, ulong divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor);
            
        }

        // Dividing ulong by ulong3
        public static bool CanDivide(ulong dividend, in ulong3 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z);
            
        }

        public static bool CanDivideBy(in ulong3 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0;
            
        }

        // Dividing ulong4 by ulong4
        public static bool CanDivide(in ulong4 dividend, in ulong4 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z)  && MathX.CanDivide(dividend.w, divisor.w) ;
            
        }

        // Dividing ulong4 by ulong
        public static bool CanDivide(in ulong4 dividend, ulong divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor) && MathX.CanDivide(dividend.w, divisor);
            
        }

        // Dividing ulong by ulong4
        public static bool CanDivide(ulong dividend, in ulong4 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z) && MathX.CanDivide(dividend, divisor.w);
            
        }

        public static bool CanDivideBy(in ulong4 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0 && divisor.w != 0;
            
        }




        public static bool CanDivideBy(int divisor)
        {
            return divisor != 0;
        }

        public static bool CanDivide(int dividend, int divisor)
        {
                 
            if (dividend == int.MinValue && divisor == -1)
                return false;
            
            return divisor != 0;
        }

        // Dividing int2 by int2
        public static bool CanDivide(in int2 dividend, in int2 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y);
            
        }

        // Dividing int2 by int
        public static bool CanDivide(in int2 dividend, int divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor);
            
        }

        // Dividing int by int2
        public static bool CanDivide(int dividend, in int2 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y);
            
        }

        public static bool CanDivideBy(in int2 divisor)
        {
            return divisor.x != 0 && divisor.y != 0;
            
        }

        // Dividing int3 by int3
        public static bool CanDivide(in int3 dividend, in int3 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z) ;
            
        }

        // Dividing int3 by int
        public static bool CanDivide(in int3 dividend, int divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor);
            
        }

        // Dividing int by int3
        public static bool CanDivide(int dividend, in int3 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z);
            
        }

        public static bool CanDivideBy(in int3 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0;
            
        }

        // Dividing int4 by int4
        public static bool CanDivide(in int4 dividend, in int4 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z)  && MathX.CanDivide(dividend.w, divisor.w) ;
            
        }

        // Dividing int4 by int
        public static bool CanDivide(in int4 dividend, int divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor) && MathX.CanDivide(dividend.w, divisor);
            
        }

        // Dividing int by int4
        public static bool CanDivide(int dividend, in int4 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z) && MathX.CanDivide(dividend, divisor.w);
            
        }

        public static bool CanDivideBy(in int4 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0 && divisor.w != 0;
            
        }




        public static bool CanDivideBy(long divisor)
        {
            return divisor != 0;
        }

        public static bool CanDivide(long dividend, long divisor)
        {
                 
            if (dividend == long.MinValue && divisor == -1)
                return false;
            
            return divisor != 0;
        }

        // Dividing long2 by long2
        public static bool CanDivide(in long2 dividend, in long2 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y);
            
        }

        // Dividing long2 by long
        public static bool CanDivide(in long2 dividend, long divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor);
            
        }

        // Dividing long by long2
        public static bool CanDivide(long dividend, in long2 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y);
            
        }

        public static bool CanDivideBy(in long2 divisor)
        {
            return divisor.x != 0 && divisor.y != 0;
            
        }

        // Dividing long3 by long3
        public static bool CanDivide(in long3 dividend, in long3 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z) ;
            
        }

        // Dividing long3 by long
        public static bool CanDivide(in long3 dividend, long divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor);
            
        }

        // Dividing long by long3
        public static bool CanDivide(long dividend, in long3 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z);
            
        }

        public static bool CanDivideBy(in long3 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0;
            
        }

        // Dividing long4 by long4
        public static bool CanDivide(in long4 dividend, in long4 divisor)
        {
            return MathX.CanDivide(dividend.x, divisor.x) && MathX.CanDivide(dividend.y, divisor.y) && MathX.CanDivide(dividend.z, divisor.z)  && MathX.CanDivide(dividend.w, divisor.w) ;
            
        }

        // Dividing long4 by long
        public static bool CanDivide(in long4 dividend, long divisor)
        {
            return MathX.CanDivide(dividend.x, divisor) && MathX.CanDivide(dividend.y, divisor) && MathX.CanDivide(dividend.z, divisor) && MathX.CanDivide(dividend.w, divisor);
            
        }

        // Dividing long by long4
        public static bool CanDivide(long dividend, in long4 divisor )
        {
            return MathX.CanDivide(dividend, divisor.x) && MathX.CanDivide(dividend, divisor.y) && MathX.CanDivide(dividend, divisor.z) && MathX.CanDivide(dividend, divisor.w);
            
        }

        public static bool CanDivideBy(in long4 divisor)
        {
            return divisor.x != 0 && divisor.y != 0 && divisor.z != 0 && divisor.w != 0;
            
        }




      

    }
}
