// Autogenerated!!! DO NOT MODIFY!
// Generated on: 12/11/2025 14:49:33

using System;
using System.Runtime.CompilerServices;

namespace Elements.Core
{

public static partial class MathX
{
 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Acos( double d )
			{
				return Math.Acos( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Acos( float d )
			{
				return MathF.Acos( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Acosh( double d )
			{
				return Math.Acosh( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Acosh( float d )
			{
				return MathF.Acosh( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Asin( double d )
			{
				return Math.Asin( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Asin( float d )
			{
				return MathF.Asin( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Asinh( double d )
			{
				return Math.Asinh( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Asinh( float d )
			{
				return MathF.Asinh( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Atan( double d )
			{
				return Math.Atan( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Atan( float d )
			{
				return MathF.Atan( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Atanh( double d )
			{
				return Math.Atanh( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Atanh( float d )
			{
				return MathF.Atanh( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Atan2( double y,double x )
			{
				return Math.Atan2( y, x);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Atan2( float y,float x )
			{
				return MathF.Atan2( y, x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Cbrt( double d )
			{
				return Math.Cbrt( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Cbrt( float d )
			{
				return MathF.Cbrt( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Ceil( double a )
			{
				return Math.Ceiling( a);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Ceil( float a )
			{
				return MathF.Ceiling( a);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Cos( double d )
			{
				return Math.Cos( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Cos( float d )
			{
				return MathF.Cos( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Cosh( double value )
			{
				return Math.Cosh( value);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Cosh( float value )
			{
				return MathF.Cosh( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Exp( double d )
			{
				return Math.Exp( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Exp( float d )
			{
				return MathF.Exp( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Floor( double d )
			{
				return Math.Floor( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Floor( float d )
			{
				return MathF.Floor( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double FusedMultiplyAdd( double x,double y,double z )
			{
				return Math.FusedMultiplyAdd( x, y, z);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float FusedMultiplyAdd( float x,float y,float z )
			{
				return MathF.FusedMultiplyAdd( x, y, z);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Log( double d )
			{
				return Math.Log( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Log( float d )
			{
				return MathF.Log( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Log2( double x )
			{
				return Math.Log2( x);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Log2( float x )
			{
				return MathF.Log2( x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Log10( double d )
			{
				return Math.Log10( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Log10( float d )
			{
				return MathF.Log10( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Pow( double x,double y )
			{
				return Math.Pow( x, y);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Pow( float x,float y )
			{
				return MathF.Pow( x, y);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Sin( double a )
			{
				return Math.Sin( a);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Sin( float a )
			{
				return MathF.Sin( a);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (double Sin, double Cos) SinCos( double x )
			{
				return Math.SinCos( x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Sinh( double value )
			{
				return Math.Sinh( value);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Sinh( float value )
			{
				return MathF.Sinh( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Sqrt( double d )
			{
				return Math.Sqrt( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Sqrt( float d )
			{
				return MathF.Sqrt( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Tan( double a )
			{
				return Math.Tan( a);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Tan( float a )
			{
				return MathF.Tan( a);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Tanh( double value )
			{
				return Math.Tanh( value);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Tanh( float value )
			{
				return MathF.Tanh( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static short Abs( short value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Abs( int value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long Abs( long value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static IntPtr Abs( IntPtr value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static sbyte Abs( sbyte value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Abs( decimal value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Abs( double value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Abs( float value )
			{
				return Math.Abs( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ulong BigMul( uint a,uint b )
			{
				return Math.BigMul( a, b);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long BigMul( int a,int b )
			{
				return Math.BigMul( a, b);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ulong BigMul( ulong a,ulong b,out ulong low )
			{
				return Math.BigMul( a, b,out  low);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long BigMul( long a,long b,out long low )
			{
				return Math.BigMul( a, b,out  low);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static UInt128 BigMul( ulong a,ulong b )
			{
				return Math.BigMul( a, b);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static Int128 BigMul( long a,long b )
			{
				return Math.BigMul( a, b);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double BitDecrement( double x )
			{
				return Math.BitDecrement( x);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float BitDecrement( float x )
			{
				return MathF.BitDecrement( x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double BitIncrement( double x )
			{
				return Math.BitIncrement( x);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float BitIncrement( float x )
			{
				return MathF.BitIncrement( x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double CopySign( double x,double y )
			{
				return Math.CopySign( x, y);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float CopySign( float x,float y )
			{
				return MathF.CopySign( x, y);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int DivRem( int a,int b,out int result )
			{
				return Math.DivRem( a, b,out  result);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long DivRem( long a,long b,out long result )
			{
				return Math.DivRem( a, b,out  result);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (sbyte Quotient, sbyte Remainder) DivRem( sbyte left,sbyte right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (byte Quotient, byte Remainder) DivRem( byte left,byte right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (short Quotient, short Remainder) DivRem( short left,short right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (ushort Quotient, ushort Remainder) DivRem( ushort left,ushort right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (int Quotient, int Remainder) DivRem( int left,int right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (uint Quotient, uint Remainder) DivRem( uint left,uint right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (long Quotient, long Remainder) DivRem( long left,long right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (ulong Quotient, ulong Remainder) DivRem( ulong left,ulong right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (IntPtr Quotient, IntPtr Remainder) DivRem( IntPtr left,IntPtr right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static (UIntPtr Quotient, UIntPtr Remainder) DivRem( UIntPtr left,UIntPtr right )
			{
				return Math.DivRem( left, right);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Ceil( decimal d )
			{
				return Math.Ceiling( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Floor( decimal d )
			{
				return Math.Floor( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double IEEERemainder( double x,double y )
			{
				return Math.IEEERemainder( x, y);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float IEEERemainder( float x,float y )
			{
				return MathF.IEEERemainder( x, y);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int ILogB( double x )
			{
				return Math.ILogB( x);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Log( double a,double newBase )
			{
				return Math.Log( a, newBase);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Log( float a,float newBase )
			{
				return MathF.Log( a, newBase);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static byte Max( byte val1,byte val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Max( decimal val1,decimal val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Max( double val1,double val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static short Max( short val1,short val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Max( int val1,int val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long Max( long val1,long val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static IntPtr Max( IntPtr val1,IntPtr val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static sbyte Max( sbyte val1,sbyte val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Max( float val1,float val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ushort Max( ushort val1,ushort val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static uint Max( uint val1,uint val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ulong Max( ulong val1,ulong val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static UIntPtr Max( UIntPtr val1,UIntPtr val2 )
			{
				return Math.Max( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double MaxMagnitude( double x,double y )
			{
				return Math.MaxMagnitude( x, y);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float MaxMagnitude( float x,float y )
			{
				return MathF.MaxMagnitude( x, y);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static byte Min( byte val1,byte val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Min( decimal val1,decimal val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Min( double val1,double val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static short Min( short val1,short val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Min( int val1,int val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static long Min( long val1,long val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static IntPtr Min( IntPtr val1,IntPtr val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static sbyte Min( sbyte val1,sbyte val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Min( float val1,float val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ushort Min( ushort val1,ushort val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static uint Min( uint val1,uint val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ulong Min( ulong val1,ulong val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static UIntPtr Min( UIntPtr val1,UIntPtr val2 )
			{
				return Math.Min( val1, val2);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double MinMagnitude( double x,double y )
			{
				return Math.MinMagnitude( x, y);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float MinMagnitude( float x,float y )
			{
				return MathF.MinMagnitude( x, y);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double ReciprocalEstimate( double d )
			{
				return Math.ReciprocalEstimate( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float ReciprocalEstimate( float d )
			{
				return MathF.ReciprocalEstimate( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double ReciprocalSqrtEstimate( double d )
			{
				return Math.ReciprocalSqrtEstimate( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float ReciprocalSqrtEstimate( float d )
			{
				return MathF.ReciprocalSqrtEstimate( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Round( decimal d )
			{
				return Math.Round( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Round( decimal d,int decimals )
			{
				return Math.Round( d, decimals);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Round( decimal d,MidpointRounding mode )
			{
				return Math.Round( d, mode);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Round( decimal d,int decimals,MidpointRounding mode )
			{
				return Math.Round( d, decimals, mode);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Round( double a )
			{
				return Math.Round( a);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Round( float a )
			{
				return MathF.Round( a);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Round( double value,int digits )
			{
				return Math.Round( value, digits);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Round( float value,int digits )
			{
				return MathF.Round( value, digits);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Round( double value,MidpointRounding mode )
			{
				return Math.Round( value, mode);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Round( float value,MidpointRounding mode )
			{
				return MathF.Round( value, mode);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Round( double value,int digits,MidpointRounding mode )
			{
				return Math.Round( value, digits, mode);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Round( float value,int digits,MidpointRounding mode )
			{
				return MathF.Round( value, digits, mode);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( decimal value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( double value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( short value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( int value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( long value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( IntPtr value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( sbyte value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static int Sign( float value )
			{
				return Math.Sign( value);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static decimal Truncate( decimal d )
			{
				return Math.Truncate( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double Truncate( double d )
			{
				return Math.Truncate( d);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float Truncate( float d )
			{
				return MathF.Truncate( d);
			}

			 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static double ScaleB( double x,int n )
			{
				return Math.ScaleB( x, n);
			}

							// Float Wrapper
				 
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static float ScaleB( float x,int n )
			{
				return MathF.ScaleB( x, n);
			}

			}

}

