// Autogenerated!!! DO NOT MODIFY!
// Generated on: 02/06/2026 22:24:13

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Globalization;

namespace Elements.Core
{
    public static class RobustParser
    {
        // TODO!!! Improve robustness, trying multiple cultures and formats

                        public static bool TryParse(string str, out bool value) 
                {
                    return bool.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out byte value) 
                {
                    if(byte.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out byte value) 
                {
                    if(byte.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ushort value) 
                {
                    if(ushort.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ushort value) 
                {
                    if(ushort.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out uint value) 
                {
                    if(uint.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out uint value) 
                {
                    if(uint.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ulong value) 
                {
                    if(ulong.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ulong value) 
                {
                    if(ulong.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out sbyte value) 
                {
                    if(sbyte.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out sbyte value) 
                {
                    if(sbyte.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out short value) 
                {
                    if(short.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out short value) 
                {
                    if(short.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out int value) 
                {
                    if(int.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out int value) 
                {
                    if(int.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out long value) 
                {
                    if(long.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out long value) 
                {
                    if(long.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out float value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float.TryParse(str, style, CultureInfo.CurrentCulture, out float localValue);
                    var invariantParsed = float.TryParse(str, style, CultureInfo.InvariantCulture, out float invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double.TryParse(str, style, CultureInfo.CurrentCulture, out double localValue);
                    var invariantParsed = double.TryParse(str, style, CultureInfo.InvariantCulture, out double invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out decimal value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out decimal value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = decimal.TryParse(str, style, CultureInfo.CurrentCulture, out decimal localValue);
                    var invariantParsed = decimal.TryParse(str, style, CultureInfo.InvariantCulture, out decimal invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(decimal).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out char value) 
                {
                    return char.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out string value) 
                {
                    value = str;
                    return true;
                }
                                public static bool TryParse(string str, out Uri value)
                {
                    return Uri.TryCreate(str, UriKind.Absolute, out value);
                }
                                public static bool TryParse(string str, out bool2 value) 
                {
                    return bool2.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out byte2 value) 
                {
                    if(byte2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out byte2 value) 
                {
                    if(byte2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ushort2 value) 
                {
                    if(ushort2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ushort2 value) 
                {
                    if(ushort2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out uint2 value) 
                {
                    if(uint2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out uint2 value) 
                {
                    if(uint2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ulong2 value) 
                {
                    if(ulong2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ulong2 value) 
                {
                    if(ulong2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out sbyte2 value) 
                {
                    if(sbyte2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out sbyte2 value) 
                {
                    if(sbyte2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out short2 value) 
                {
                    if(short2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out short2 value) 
                {
                    if(short2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out int2 value) 
                {
                    if(int2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out int2 value) 
                {
                    if(int2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out long2 value) 
                {
                    if(long2.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long2.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out long2 value) 
                {
                    if(long2.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long2.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out float2 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float2 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float2.TryParse(str, style, CultureInfo.CurrentCulture, out float2 localValue);
                    var invariantParsed = float2.TryParse(str, style, CultureInfo.InvariantCulture, out float2 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float2).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double2 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double2 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double2.TryParse(str, style, CultureInfo.CurrentCulture, out double2 localValue);
                    var invariantParsed = double2.TryParse(str, style, CultureInfo.InvariantCulture, out double2 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double2).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out bool3 value) 
                {
                    return bool3.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out byte3 value) 
                {
                    if(byte3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out byte3 value) 
                {
                    if(byte3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ushort3 value) 
                {
                    if(ushort3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ushort3 value) 
                {
                    if(ushort3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out uint3 value) 
                {
                    if(uint3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out uint3 value) 
                {
                    if(uint3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ulong3 value) 
                {
                    if(ulong3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ulong3 value) 
                {
                    if(ulong3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out sbyte3 value) 
                {
                    if(sbyte3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out sbyte3 value) 
                {
                    if(sbyte3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out short3 value) 
                {
                    if(short3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out short3 value) 
                {
                    if(short3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out int3 value) 
                {
                    if(int3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out int3 value) 
                {
                    if(int3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out long3 value) 
                {
                    if(long3.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long3.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out long3 value) 
                {
                    if(long3.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long3.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out float3 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float3 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float3.TryParse(str, style, CultureInfo.CurrentCulture, out float3 localValue);
                    var invariantParsed = float3.TryParse(str, style, CultureInfo.InvariantCulture, out float3 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float3).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double3 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double3 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double3.TryParse(str, style, CultureInfo.CurrentCulture, out double3 localValue);
                    var invariantParsed = double3.TryParse(str, style, CultureInfo.InvariantCulture, out double3 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double3).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out bool4 value) 
                {
                    return bool4.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out byte4 value) 
                {
                    if(byte4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out byte4 value) 
                {
                    if(byte4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return byte4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ushort4 value) 
                {
                    if(ushort4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ushort4 value) 
                {
                    if(ushort4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ushort4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out uint4 value) 
                {
                    if(uint4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out uint4 value) 
                {
                    if(uint4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return uint4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out ulong4 value) 
                {
                    if(ulong4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out ulong4 value) 
                {
                    if(ulong4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return ulong4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out sbyte4 value) 
                {
                    if(sbyte4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out sbyte4 value) 
                {
                    if(sbyte4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return sbyte4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out short4 value) 
                {
                    if(short4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out short4 value) 
                {
                    if(short4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return short4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out int4 value) 
                {
                    if(int4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out int4 value) 
                {
                    if(int4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return int4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out long4 value) 
                {
                    if(long4.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long4.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out long4 value) 
                {
                    if(long4.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return long4.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                                public static bool TryParse(string str, out float4 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float4 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float4.TryParse(str, style, CultureInfo.CurrentCulture, out float4 localValue);
                    var invariantParsed = float4.TryParse(str, style, CultureInfo.InvariantCulture, out float4 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float4).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double4 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double4 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double4.TryParse(str, style, CultureInfo.CurrentCulture, out double4 localValue);
                    var invariantParsed = double4.TryParse(str, style, CultureInfo.InvariantCulture, out double4 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double4).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out float2x2 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float2x2 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float2x2.TryParse(str, style, CultureInfo.CurrentCulture, out float2x2 localValue);
                    var invariantParsed = float2x2.TryParse(str, style, CultureInfo.InvariantCulture, out float2x2 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float2x2).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double2x2 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double2x2 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double2x2.TryParse(str, style, CultureInfo.CurrentCulture, out double2x2 localValue);
                    var invariantParsed = double2x2.TryParse(str, style, CultureInfo.InvariantCulture, out double2x2 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double2x2).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out float3x3 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float3x3 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float3x3.TryParse(str, style, CultureInfo.CurrentCulture, out float3x3 localValue);
                    var invariantParsed = float3x3.TryParse(str, style, CultureInfo.InvariantCulture, out float3x3 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float3x3).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double3x3 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double3x3 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double3x3.TryParse(str, style, CultureInfo.CurrentCulture, out double3x3 localValue);
                    var invariantParsed = double3x3.TryParse(str, style, CultureInfo.InvariantCulture, out double3x3 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double3x3).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out float4x4 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out float4x4 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = float4x4.TryParse(str, style, CultureInfo.CurrentCulture, out float4x4 localValue);
                    var invariantParsed = float4x4.TryParse(str, style, CultureInfo.InvariantCulture, out float4x4 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(float4x4).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out double4x4 value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out double4x4 value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = double4x4.TryParse(str, style, CultureInfo.CurrentCulture, out double4x4 localValue);
                    var invariantParsed = double4x4.TryParse(str, style, CultureInfo.InvariantCulture, out double4x4 invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(double4x4).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out floatQ value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out floatQ value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = floatQ.TryParse(str, style, CultureInfo.CurrentCulture, out floatQ localValue);
                    var invariantParsed = floatQ.TryParse(str, style, CultureInfo.InvariantCulture, out floatQ invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(floatQ).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out doubleQ value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out doubleQ value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = doubleQ.TryParse(str, style, CultureInfo.CurrentCulture, out doubleQ localValue);
                    var invariantParsed = doubleQ.TryParse(str, style, CultureInfo.InvariantCulture, out doubleQ invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(doubleQ).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out System.DateTime value) 
                {
                    return System.DateTime.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out System.TimeSpan value) 
                {
                    return System.TimeSpan.TryParse(str, out value);
                }

                                public static bool TryParse(string str, out color value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out color value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = color.TryParse(str, style, CultureInfo.CurrentCulture, out color localValue);
                    var invariantParsed = color.TryParse(str, style, CultureInfo.InvariantCulture, out color invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(color).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out colorX value)  => TryParse(str, NumberStyles.Float, out value);

				public static bool TryParse(string str, NumberStyles style, out colorX value) 
                {
                    if(string.IsNullOrWhiteSpace(str))
                    {
                        value = default;
                        return false;
                    }

                    var localParsed = colorX.TryParse(str, style, CultureInfo.CurrentCulture, out colorX localValue);
                    var invariantParsed = colorX.TryParse(str, style, CultureInfo.InvariantCulture, out colorX invariantValue);

                    if(!localParsed && !invariantParsed)
                    {
                        value = default;
                        return false;
                    }

                    if(localParsed && invariantParsed)
                    {
                        // both parsed, but one is clearly wrong
                        bool useLocal = false;

                        var elementCount = typeof(colorX).GetElementCount();

                        for(int e = 0; e < elementCount; e++)
                        {
                            var l = MathX.Frac(MathX.Abs(localValue.GetElement(e)));
                            var i = MathX.Frac(MathX.Abs(invariantValue.GetElement(e)));

                            if(l == i)
                                continue;

                            if(l > i)
                            {
                                useLocal = true;
                                break;
                            }
                        }

                        if(useLocal)
                            value = localValue;
                        else
                            value = invariantValue;

                        return true;
                    }

                    if(localParsed)
                    {
                        value = localValue;
                        return true;
                    }
                    else
                    {
                        value = invariantValue;
                        return true;
                    }
                }

                                public static bool TryParse(string str, out color32 value) 
                {
                    if(color32.TryParse(str, NumberStyles.Integer, CultureInfo.CurrentCulture, out value))
                        return true;

                    return color32.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
                }

				public static bool TryParse(string str, NumberStyles style, out color32 value) 
                {
                    if(color32.TryParse(str, style, CultureInfo.CurrentCulture, out value))
                        return true;

                    return color32.TryParse(str, style, CultureInfo.InvariantCulture, out value);
                }

                    }
}
