	// Autogenerated!!! DO NOT MODIFY!
// Generated on: 09/08/2023 06:46:41
using System;

namespace Elements.Core
{
	public static partial class SignalX
	{
		// Datatype conversion  methods
		
		
					// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<byte> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)byte.MaxValue - (float)byte.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + byte.MinValue;

                    if (val >= byte.MaxValue)
                        output[i] = byte.MaxValue;
                    else if (val < byte.MinValue)
                        output[i] = byte.MinValue;
                    else
                        output[i] = (byte)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<byte> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)byte.MaxValue - (float)byte.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= byte.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
						// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<ushort> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)ushort.MaxValue - (float)ushort.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + ushort.MinValue;

                    if (val >= ushort.MaxValue)
                        output[i] = ushort.MaxValue;
                    else if (val < ushort.MinValue)
                        output[i] = ushort.MinValue;
                    else
                        output[i] = (ushort)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<ushort> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)ushort.MaxValue - (float)ushort.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= ushort.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
						// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<uint> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)uint.MaxValue - (float)uint.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + uint.MinValue;

                    if (val >= uint.MaxValue)
                        output[i] = uint.MaxValue;
                    else if (val < uint.MinValue)
                        output[i] = uint.MinValue;
                    else
                        output[i] = (uint)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<uint> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)uint.MaxValue - (float)uint.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= uint.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
						// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<sbyte> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)sbyte.MaxValue - (float)sbyte.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + sbyte.MinValue;

                    if (val >= sbyte.MaxValue)
                        output[i] = sbyte.MaxValue;
                    else if (val < sbyte.MinValue)
                        output[i] = sbyte.MinValue;
                    else
                        output[i] = (sbyte)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<sbyte> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)sbyte.MaxValue - (float)sbyte.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= sbyte.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
						// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<short> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)short.MaxValue - (float)short.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + short.MinValue;

                    if (val >= short.MaxValue)
                        output[i] = short.MaxValue;
                    else if (val < short.MinValue)
                        output[i] = short.MinValue;
                    else
                        output[i] = (short)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<short> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)short.MaxValue - (float)short.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= short.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
						// Float -1f...1f --> Datatype
			public static void Convert(Span<float> input, Span<int> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                for (int i = 0; i < input.Length; i++)
                {
                    var range = (float)int.MaxValue - (float)int.MinValue;
                    var val = (input[i] * 0.5f + 0.5f) * range + int.MinValue;

                    if (val >= int.MaxValue)
                        output[i] = int.MaxValue;
                    else if (val < int.MinValue)
                        output[i] = int.MinValue;
                    else
                        output[i] = (int)val;
                }
			}

			// Datatype --> Float -1f...1f
			public static void Convert(Span<int> input, Span<float> output)
			{
				// check ranges
                if (input.Length > output.Length)
                    throw new ArgumentOutOfRangeException();

                var mul = (1f / ((float)int.MaxValue - (float)int.MinValue)) * 2f;

                for (int i = 0; i < input.Length; i++)
                {
                    var val = (float)input[i];

                    val -= int.MinValue;
                    val *= mul;
                    val -= 1f;

                    output[i] = val;
                }
			}
				}
}
