// Autogenerated!!! DO NOT MODIFY!
// Generated on: 04/30/2024 09:42:18
using System;
using System.Globalization;

namespace Elements.Core
{
	public static class PrimitiveTryParsers
	{
		public delegate bool TryParser(string str, out object parsed);

        public static TryParser GetParser(Type type) => GetParser(type.Name);

		public static TryParser GetParser(string typename)
		{
			switch(typename)
			{
				case "Boolean": return BooleanParser;
					case "Byte": return ByteParser;
					case "UInt16": return UInt16Parser;
					case "UInt32": return UInt32Parser;
					case "UInt64": return UInt64Parser;
					case "SByte": return SByteParser;
					case "Int16": return Int16Parser;
					case "Int32": return Int32Parser;
					case "Int64": return Int64Parser;
					case "Single": return SingleParser;
					case "Double": return DoubleParser;
					case "Decimal": return DecimalParser;
					case "Char": return CharParser;
					case "Uri": return UriParser;
					
				case "String": return _stringParser;
				case "Type": return TypeParser;

				default:
					throw new Exception("Type is not supported: " + typename);
			}
		}

		// for completeness
		static TryParser _stringParser = delegate(string str, out object parsed)
		{
			parsed = str;
			return true;
		};

		// not technically a primitive, but used as such 
		public static readonly TryParser UriParser = delegate(string str, out object parsed)
		{
			if(string.IsNullOrWhiteSpace(str))
			{
				parsed =  null;
				return true;
			}

			if(Uri.TryCreate(str, UriKind.Absolute, out Uri uri))
			{
				parsed = uri;
				return true;
			}

			parsed = null;
			return false;
		};

		public static readonly TryParser TypeParser = delegate(string str, out object parsed)
		{
			if(string.IsNullOrWhiteSpace(str))
			{
				parsed = null;
				return true;
			}

			parsed = NiceTypeParser.TryParse(str);
			return parsed != null;
		};

		public static readonly TryParser BooleanParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str,  out bool result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser ByteParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out byte result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser UInt16Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out ushort result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser UInt32Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out uint result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser UInt64Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out ulong result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser SByteParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out sbyte result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser Int16Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out short result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser Int32Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out int result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser Int64Parser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out long result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser SingleParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out float result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser DoubleParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out double result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser DecimalParser = delegate(string str, out object parsed)
			{
                
				if(RobustParser.TryParse(str, NumberStyles.Any,  out decimal result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
			public static readonly TryParser CharParser = delegate(string str, out object parsed)
			{
                                    if(str != null && str.Length > 1 && str[0] == '\0')
                        str = str.Substring(1);
                    
				if(RobustParser.TryParse(str,  out char result))
				{
					parsed = result;
					return true;
				}

				parsed = null;
				return false;
			};
				}
}
