// Autogenerated!!! DO NOT MODIFY!
// Generated on: 08/27/2025 12:49:10

global using half = System.Half;

using System;
using System.IO;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using System.Numerics;
using Elements.Core; using Elements.Data;
using JsonIgnore = System.Text.Json.Serialization.JsonIgnoreAttribute;

// These are half variants of vectors
// These are currently stripped down versions of the full vectors with minimal support
// This is done because we don't really want to do math in those, as half is emulated
// They are mostly there to support raw data exchange with the GPU

namespace Elements.Core;


    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public readonly struct half2 : IVector<half>, IEquatable<half2>
    {
        public const int DIMENSIONS = 2;
        public static readonly Type BASE_TYPE = typeof(half);
        public const string BASE_TYPENAME = "half";
        public static readonly half COMPONENT_RATIO = (half)(1f / 2);

        		        public readonly half x;

				[JsonPropertyName("x")]
				[JsonProperty(PropertyName = "x")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half X => x;
                		        public readonly half y;

				[JsonPropertyName("y")]
				[JsonProperty(PropertyName = "y")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half Y => y;
                
        [JsonIgnore]
	    public int Dimensions => DIMENSIONS;

        [JsonIgnore]
	    public readonly Type ElementType => typeof(half);

        public readonly half this[int n]
	    {
		    [MethodImpl(MethodImplOptions.AggressiveInlining)]
		    get
		    {
			    switch(n)
			    {
				    case 0: return x;
				case 1: return y;
				
				    default: return default;
			    }
		    }
	    }

        public readonly object GetBoxedElement(int n) => this[n];

        public readonly object GetWithElementsAveraged()
        {
            var c = (half)MathX.AvgComponent(this);
            return new half2(c,c);
        }

        public readonly object GetWithAllElementsSetTo(int n)
        {
            var c = this[n];
            return new half2(c,c);
        }

        public override bool Equals(object other)
	    {
		    if(other is half2)
			    return Equals((half2)other);
		    return false;
	    }

	    public bool Equals(half2 other)
	    {
		    return x==other.x&&y==other.y;
	    }

	    public override int GetHashCode()
	    {
		    unchecked
		    {
			    var hash = x.GetHashCode();
					    hash = (hash*397) ^ y.GetHashCode();
					    
			    return hash;
		    }
	    }

#region CONSTRUCTORS

        [System.Text.Json.Serialization.JsonConstructor]
	    [Newtonsoft.Json.JsonConstructor]
	    public half2(half x = default(half), half y = default(half))
	    {
    				        this.x = x;
		    		        this.y = y;
		    	    }

	    public half2(half2 xy)
	    {
            this = xy;
	    }

	    
	    
#endregion

#region CASTING

        // Half <---> Float
        public static implicit operator float2(in half2 v) => new float2((float)v.x,(float)v.y);
		public static explicit operator half2(in float2 v) => new half2((half)v.x,(half)v.y);

        // Half <---> 
        public static implicit operator double2(in half2 v) => new double2((double)v.x,(double)v.y);
		public static explicit operator half2(in double2 v) => new half2((half)v.x,(half)v.y);

#endregion

    }

    public static partial class MathX
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static half AvgComponent(in half2 v)
		{
			return (v.x + v.y) * half2.COMPONENT_RATIO;
		}
    }
    
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public readonly struct half3 : IVector<half>, IEquatable<half3>
    {
        public const int DIMENSIONS = 3;
        public static readonly Type BASE_TYPE = typeof(half);
        public const string BASE_TYPENAME = "half";
        public static readonly half COMPONENT_RATIO = (half)(1f / 3);

        		        public readonly half x;

				[JsonPropertyName("x")]
				[JsonProperty(PropertyName = "x")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half X => x;
                		        public readonly half y;

				[JsonPropertyName("y")]
				[JsonProperty(PropertyName = "y")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half Y => y;
                		        public readonly half z;

				[JsonPropertyName("z")]
				[JsonProperty(PropertyName = "z")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half Z => z;
                
        [JsonIgnore]
	    public int Dimensions => DIMENSIONS;

        [JsonIgnore]
	    public readonly Type ElementType => typeof(half);

        public readonly half this[int n]
	    {
		    [MethodImpl(MethodImplOptions.AggressiveInlining)]
		    get
		    {
			    switch(n)
			    {
				    case 0: return x;
				case 1: return y;
				case 2: return z;
				
				    default: return default;
			    }
		    }
	    }

        public readonly object GetBoxedElement(int n) => this[n];

        public readonly object GetWithElementsAveraged()
        {
            var c = (half)MathX.AvgComponent(this);
            return new half3(c,c,c);
        }

        public readonly object GetWithAllElementsSetTo(int n)
        {
            var c = this[n];
            return new half3(c,c,c);
        }

        public override bool Equals(object other)
	    {
		    if(other is half3)
			    return Equals((half3)other);
		    return false;
	    }

	    public bool Equals(half3 other)
	    {
		    return x==other.x&&y==other.y&&z==other.z;
	    }

	    public override int GetHashCode()
	    {
		    unchecked
		    {
			    var hash = x.GetHashCode();
					    hash = (hash*397) ^ y.GetHashCode();
					    hash = (hash*397) ^ z.GetHashCode();
					    
			    return hash;
		    }
	    }

#region CONSTRUCTORS

        [System.Text.Json.Serialization.JsonConstructor]
	    [Newtonsoft.Json.JsonConstructor]
	    public half3(half x = default(half), half y = default(half), half z = default(half))
	    {
    				        this.x = x;
		    		        this.y = y;
		    		        this.z = z;
		    	    }

	    public half3(half3 xyz)
	    {
            this = xyz;
	    }

	    
		    public half3(in half2 xy, half z) : this(xy.x, xy.y, z)
		    {
		    }

		    public half3(half x, in half2 yz) : this(x, yz.x, yz.y)
		    {
		    }

		    
	    
#endregion

#region CASTING

        // Half <---> Float
        public static implicit operator float3(in half3 v) => new float3((float)v.x,(float)v.y,(float)v.z);
		public static explicit operator half3(in float3 v) => new half3((half)v.x,(half)v.y,(half)v.z);

        // Half <---> 
        public static implicit operator double3(in half3 v) => new double3((double)v.x,(double)v.y,(double)v.z);
		public static explicit operator half3(in double3 v) => new half3((half)v.x,(half)v.y,(half)v.z);

#endregion

    }

    public static partial class MathX
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static half AvgComponent(in half3 v)
		{
			return (v.x + v.y + v.z) * half3.COMPONENT_RATIO;
		}
    }
    
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public readonly struct half4 : IVector<half>, IEquatable<half4>
    {
        public const int DIMENSIONS = 4;
        public static readonly Type BASE_TYPE = typeof(half);
        public const string BASE_TYPENAME = "half";
        public static readonly half COMPONENT_RATIO = (half)(1f / 4);

        		        public readonly half x;

				[JsonPropertyName("x")]
				[JsonProperty(PropertyName = "x")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half X => x;
                		        public readonly half y;

				[JsonPropertyName("y")]
				[JsonProperty(PropertyName = "y")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half Y => y;
                		        public readonly half z;

				[JsonPropertyName("z")]
				[JsonProperty(PropertyName = "z")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half Z => z;
                		        public readonly half w;

				[JsonPropertyName("w")]
				[JsonProperty(PropertyName = "w")]
				[DebuggerBrowsable(DebuggerBrowsableState.Never)]
				public readonly half W => w;
                
        [JsonIgnore]
	    public int Dimensions => DIMENSIONS;

        [JsonIgnore]
	    public readonly Type ElementType => typeof(half);

        public readonly half this[int n]
	    {
		    [MethodImpl(MethodImplOptions.AggressiveInlining)]
		    get
		    {
			    switch(n)
			    {
				    case 0: return x;
				case 1: return y;
				case 2: return z;
				case 3: return w;
				
				    default: return default;
			    }
		    }
	    }

        public readonly object GetBoxedElement(int n) => this[n];

        public readonly object GetWithElementsAveraged()
        {
            var c = (half)MathX.AvgComponent(this);
            return new half4(c,c,c,c);
        }

        public readonly object GetWithAllElementsSetTo(int n)
        {
            var c = this[n];
            return new half4(c,c,c,c);
        }

        public override bool Equals(object other)
	    {
		    if(other is half4)
			    return Equals((half4)other);
		    return false;
	    }

	    public bool Equals(half4 other)
	    {
		    return x==other.x&&y==other.y&&z==other.z&&w==other.w;
	    }

	    public override int GetHashCode()
	    {
		    unchecked
		    {
			    var hash = x.GetHashCode();
					    hash = (hash*397) ^ y.GetHashCode();
					    hash = (hash*397) ^ z.GetHashCode();
					    hash = (hash*397) ^ w.GetHashCode();
					    
			    return hash;
		    }
	    }

#region CONSTRUCTORS

        [System.Text.Json.Serialization.JsonConstructor]
	    [Newtonsoft.Json.JsonConstructor]
	    public half4(half x = default(half), half y = default(half), half z = default(half), half w = default(half))
	    {
    				        this.x = x;
		    		        this.y = y;
		    		        this.z = z;
		    		        this.w = w;
		    	    }

	    public half4(half4 xyzw)
	    {
            this = xyzw;
	    }

	    
	    
		    public half4(in half2 xy, half z, half w) : this(xy.x, xy.y, z, w)
		    {
		    }

		    public half4(half x, in half2 yz, half w) : this(x, yz.x, yz.y, w)
		    {
		    }

		    public half4(half x, half y, in half2 zw) : this(x, y, zw.x, zw.y)
		    {
		    }

		    public half4(in half2 xy, in half2 zw) : this(xy.x, xy.y, zw.x, zw.y)
		    {
		    }

		    public half4(in half3 xyz, half w) : this(xyz.x, xyz.y, xyz.z, w)
		    {
		    }

		    public half4(half x, in half3 yzw) : this(x, yzw.x, yzw.y, yzw.z)
		    {
		    }

		    
#endregion

#region CASTING

        // Half <---> Float
        public static implicit operator float4(in half4 v) => new float4((float)v.x,(float)v.y,(float)v.z,(float)v.w);
		public static explicit operator half4(in float4 v) => new half4((half)v.x,(half)v.y,(half)v.z,(half)v.w);

        // Half <---> 
        public static implicit operator double4(in half4 v) => new double4((double)v.x,(double)v.y,(double)v.z,(double)v.w);
		public static explicit operator half4(in double4 v) => new half4((half)v.x,(half)v.y,(half)v.z,(half)v.w);

#endregion

    }

    public static partial class MathX
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static half AvgComponent(in half4 v)
		{
			return (v.x + v.y + v.z + v.w) * half4.COMPONENT_RATIO;
		}
    }
    