// Autogenerated!!! DO NOT MODIFY!
// Generated on: 02/06/2026 22:36:53

using System;

namespace Elements.Core
{
	public partial class DataTreeDictionary
	{
		#region EXTRACTING VALUES

		T ExtractValue<T>(DataTreeNode node)
		{
			var exType = typeof(T);

			if(exType.IsEnum)
				return (T)Enum.Parse(exType, ExtractValue<string>(node));
			else if(exType == typeof(string))
				return (T)(object)(node as DataTreeValue).Extract<string>();
			else if(exType == typeof(bool))
					return (T)(object)node.LoadBool();
				else if(exType == typeof(byte))
					return (T)(object)node.LoadByte();
				else if(exType == typeof(ushort))
					return (T)(object)node.LoadUshort();
				else if(exType == typeof(uint))
					return (T)(object)node.LoadUint();
				else if(exType == typeof(ulong))
					return (T)(object)node.LoadUlong();
				else if(exType == typeof(sbyte))
					return (T)(object)node.LoadSbyte();
				else if(exType == typeof(short))
					return (T)(object)node.LoadShort();
				else if(exType == typeof(int))
					return (T)(object)node.LoadInt();
				else if(exType == typeof(long))
					return (T)(object)node.LoadLong();
				else if(exType == typeof(float))
					return (T)(object)node.LoadFloat();
				else if(exType == typeof(double))
					return (T)(object)node.LoadDouble();
				else if(exType == typeof(decimal))
					return (T)(object)node.LoadDecimal();
				else if(exType == typeof(char))
					return (T)(object)node.LoadChar();
				else if(exType == typeof(string))
					return (T)(object)node.LoadString();
				else if(exType == typeof(Uri))
					return (T)(object)node.LoadUri();
				else if(exType == typeof(bool2))
					return (T)(object)node.LoadBool2();
				else if(exType == typeof(byte2))
					return (T)(object)node.LoadByte2();
				else if(exType == typeof(ushort2))
					return (T)(object)node.LoadUshort2();
				else if(exType == typeof(uint2))
					return (T)(object)node.LoadUint2();
				else if(exType == typeof(ulong2))
					return (T)(object)node.LoadUlong2();
				else if(exType == typeof(sbyte2))
					return (T)(object)node.LoadSbyte2();
				else if(exType == typeof(short2))
					return (T)(object)node.LoadShort2();
				else if(exType == typeof(int2))
					return (T)(object)node.LoadInt2();
				else if(exType == typeof(long2))
					return (T)(object)node.LoadLong2();
				else if(exType == typeof(float2))
					return (T)(object)node.LoadFloat2();
				else if(exType == typeof(double2))
					return (T)(object)node.LoadDouble2();
				else if(exType == typeof(bool3))
					return (T)(object)node.LoadBool3();
				else if(exType == typeof(byte3))
					return (T)(object)node.LoadByte3();
				else if(exType == typeof(ushort3))
					return (T)(object)node.LoadUshort3();
				else if(exType == typeof(uint3))
					return (T)(object)node.LoadUint3();
				else if(exType == typeof(ulong3))
					return (T)(object)node.LoadUlong3();
				else if(exType == typeof(sbyte3))
					return (T)(object)node.LoadSbyte3();
				else if(exType == typeof(short3))
					return (T)(object)node.LoadShort3();
				else if(exType == typeof(int3))
					return (T)(object)node.LoadInt3();
				else if(exType == typeof(long3))
					return (T)(object)node.LoadLong3();
				else if(exType == typeof(float3))
					return (T)(object)node.LoadFloat3();
				else if(exType == typeof(double3))
					return (T)(object)node.LoadDouble3();
				else if(exType == typeof(bool4))
					return (T)(object)node.LoadBool4();
				else if(exType == typeof(byte4))
					return (T)(object)node.LoadByte4();
				else if(exType == typeof(ushort4))
					return (T)(object)node.LoadUshort4();
				else if(exType == typeof(uint4))
					return (T)(object)node.LoadUint4();
				else if(exType == typeof(ulong4))
					return (T)(object)node.LoadUlong4();
				else if(exType == typeof(sbyte4))
					return (T)(object)node.LoadSbyte4();
				else if(exType == typeof(short4))
					return (T)(object)node.LoadShort4();
				else if(exType == typeof(int4))
					return (T)(object)node.LoadInt4();
				else if(exType == typeof(long4))
					return (T)(object)node.LoadLong4();
				else if(exType == typeof(float4))
					return (T)(object)node.LoadFloat4();
				else if(exType == typeof(double4))
					return (T)(object)node.LoadDouble4();
				else if(exType == typeof(float2x2))
					return (T)(object)node.LoadFloat2x2();
				else if(exType == typeof(double2x2))
					return (T)(object)node.LoadDouble2x2();
				else if(exType == typeof(float3x3))
					return (T)(object)node.LoadFloat3x3();
				else if(exType == typeof(double3x3))
					return (T)(object)node.LoadDouble3x3();
				else if(exType == typeof(float4x4))
					return (T)(object)node.LoadFloat4x4();
				else if(exType == typeof(double4x4))
					return (T)(object)node.LoadDouble4x4();
				else if(exType == typeof(floatQ))
					return (T)(object)node.LoadFloatQ();
				else if(exType == typeof(doubleQ))
					return (T)(object)node.LoadDoubleQ();
				else if(exType == typeof(System.DateTime))
					return (T)(object)node.LoadDateTime();
				else if(exType == typeof(System.TimeSpan))
					return (T)(object)node.LoadTimeSpan();
				else if(exType == typeof(color))
					return (T)(object)node.LoadColor();
				else if(exType == typeof(colorX))
					return (T)(object)node.LoadColorX();
				else if(exType == typeof(color32))
					return (T)(object)node.LoadColor32();
							else
				throw new Exception($"DataType {exType} isn't supported");
		}

		#endregion

		#region QUICK VALUE ADDERS

		public void Add<T>(string key, T val)
		{
			var type = typeof(T);

			if(val is DataTreeNode)
				Children.Add(key, val as DataTreeNode);
			else if(type.IsEnum)
				Children.Add(key, DataTreeValue.FromEnum(val));
			else if(type == typeof(string))
				Children.Add(key, new DataTreeValue((string)(object)val));
			else if(val is bool)
						Children.Add(key, ((bool)(object)val).Save());
					else if(val is byte)
						Children.Add(key, ((byte)(object)val).Save());
					else if(val is ushort)
						Children.Add(key, ((ushort)(object)val).Save());
					else if(val is uint)
						Children.Add(key, ((uint)(object)val).Save());
					else if(val is ulong)
						Children.Add(key, ((ulong)(object)val).Save());
					else if(val is sbyte)
						Children.Add(key, ((sbyte)(object)val).Save());
					else if(val is short)
						Children.Add(key, ((short)(object)val).Save());
					else if(val is int)
						Children.Add(key, ((int)(object)val).Save());
					else if(val is long)
						Children.Add(key, ((long)(object)val).Save());
					else if(val is float)
						Children.Add(key, ((float)(object)val).Save());
					else if(val is double)
						Children.Add(key, ((double)(object)val).Save());
					else if(val is decimal)
						Children.Add(key, ((decimal)(object)val).Save());
					else if(val is char)
						Children.Add(key, ((char)(object)val).Save());
					else if(val is string)
						Children.Add(key, ((string)(object)val).Save());
					else if(val is Uri)
						Children.Add(key, ((Uri)(object)val).Save());
					else if(val is bool2)
						Children.Add(key, ((bool2)(object)val).Save());
					else if(val is byte2)
						Children.Add(key, ((byte2)(object)val).Save());
					else if(val is ushort2)
						Children.Add(key, ((ushort2)(object)val).Save());
					else if(val is uint2)
						Children.Add(key, ((uint2)(object)val).Save());
					else if(val is ulong2)
						Children.Add(key, ((ulong2)(object)val).Save());
					else if(val is sbyte2)
						Children.Add(key, ((sbyte2)(object)val).Save());
					else if(val is short2)
						Children.Add(key, ((short2)(object)val).Save());
					else if(val is int2)
						Children.Add(key, ((int2)(object)val).Save());
					else if(val is long2)
						Children.Add(key, ((long2)(object)val).Save());
					else if(val is float2)
						Children.Add(key, ((float2)(object)val).Save());
					else if(val is double2)
						Children.Add(key, ((double2)(object)val).Save());
					else if(val is bool3)
						Children.Add(key, ((bool3)(object)val).Save());
					else if(val is byte3)
						Children.Add(key, ((byte3)(object)val).Save());
					else if(val is ushort3)
						Children.Add(key, ((ushort3)(object)val).Save());
					else if(val is uint3)
						Children.Add(key, ((uint3)(object)val).Save());
					else if(val is ulong3)
						Children.Add(key, ((ulong3)(object)val).Save());
					else if(val is sbyte3)
						Children.Add(key, ((sbyte3)(object)val).Save());
					else if(val is short3)
						Children.Add(key, ((short3)(object)val).Save());
					else if(val is int3)
						Children.Add(key, ((int3)(object)val).Save());
					else if(val is long3)
						Children.Add(key, ((long3)(object)val).Save());
					else if(val is float3)
						Children.Add(key, ((float3)(object)val).Save());
					else if(val is double3)
						Children.Add(key, ((double3)(object)val).Save());
					else if(val is bool4)
						Children.Add(key, ((bool4)(object)val).Save());
					else if(val is byte4)
						Children.Add(key, ((byte4)(object)val).Save());
					else if(val is ushort4)
						Children.Add(key, ((ushort4)(object)val).Save());
					else if(val is uint4)
						Children.Add(key, ((uint4)(object)val).Save());
					else if(val is ulong4)
						Children.Add(key, ((ulong4)(object)val).Save());
					else if(val is sbyte4)
						Children.Add(key, ((sbyte4)(object)val).Save());
					else if(val is short4)
						Children.Add(key, ((short4)(object)val).Save());
					else if(val is int4)
						Children.Add(key, ((int4)(object)val).Save());
					else if(val is long4)
						Children.Add(key, ((long4)(object)val).Save());
					else if(val is float4)
						Children.Add(key, ((float4)(object)val).Save());
					else if(val is double4)
						Children.Add(key, ((double4)(object)val).Save());
					else if(val is float2x2)
						Children.Add(key, ((float2x2)(object)val).Save());
					else if(val is double2x2)
						Children.Add(key, ((double2x2)(object)val).Save());
					else if(val is float3x3)
						Children.Add(key, ((float3x3)(object)val).Save());
					else if(val is double3x3)
						Children.Add(key, ((double3x3)(object)val).Save());
					else if(val is float4x4)
						Children.Add(key, ((float4x4)(object)val).Save());
					else if(val is double4x4)
						Children.Add(key, ((double4x4)(object)val).Save());
					else if(val is floatQ)
						Children.Add(key, ((floatQ)(object)val).Save());
					else if(val is doubleQ)
						Children.Add(key, ((doubleQ)(object)val).Save());
					else if(val is System.DateTime)
						Children.Add(key, ((System.DateTime)(object)val).Save());
					else if(val is System.TimeSpan)
						Children.Add(key, ((System.TimeSpan)(object)val).Save());
					else if(val is color)
						Children.Add(key, ((color)(object)val).Save());
					else if(val is colorX)
						Children.Add(key, ((colorX)(object)val).Save());
					else if(val is color32)
						Children.Add(key, ((color32)(object)val).Save());
					
			else
				throw new Exception($"Type {type} isn't supported.");
		}


		#endregion
	}
}
