// Autogenerated!!! DO NOT MODIFY!
// Generated on: 02/06/2026 22:09:00

using System;
using System.IO;
using Renderite.Shared;

namespace Elements.Core
{

public static class LoadSaveHelper
{


	public static DataTreeNode Save(this bool value)
	{
					return new DataTreeValue(value);
			}

	public static bool LoadBool(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<bool>();
						}

	
	public static DataTreeNode Save(this byte value)
	{
					return new DataTreeValue(value);
			}

	public static byte LoadByte(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<byte>();
						}

	
	public static DataTreeNode Save(this ushort value)
	{
					return new DataTreeValue(value);
			}

	public static ushort LoadUshort(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<ushort>();
						}

	
	public static DataTreeNode Save(this uint value)
	{
					return new DataTreeValue(value);
			}

	public static uint LoadUint(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<uint>();
						}

	
	public static DataTreeNode Save(this ulong value)
	{
					return new DataTreeValue(value);
			}

	public static ulong LoadUlong(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<ulong>();
						}

	
	public static DataTreeNode Save(this sbyte value)
	{
					return new DataTreeValue(value);
			}

	public static sbyte LoadSbyte(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<sbyte>();
						}

	
	public static DataTreeNode Save(this short value)
	{
					return new DataTreeValue(value);
			}

	public static short LoadShort(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<short>();
						}

	
	public static DataTreeNode Save(this int value)
	{
					return new DataTreeValue(value);
			}

	public static int LoadInt(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<int>();
						}

	
	public static DataTreeNode Save(this long value)
	{
					return new DataTreeValue(value);
			}

	public static long LoadLong(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<long>();
						}

	
	public static DataTreeNode Save(this float value)
	{
					return new DataTreeValue(value);
			}

	public static float LoadFloat(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<float>();
						}

	
	public static DataTreeNode Save(this double value)
	{
					return new DataTreeValue(value);
			}

	public static double LoadDouble(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<double>();
						}

	
	public static DataTreeNode Save(this decimal value)
	{
					return new DataTreeValue(value.ToString(System.Globalization.CultureInfo.InvariantCulture));
			}

	public static decimal LoadDecimal(this DataTreeNode node)
	{
		
					var valuenode = node as DataTreeValue;

					var str = "";

					if(!valuenode.IsNull)
						str = valuenode.Extract<string>();

					RobustParser.TryParse(str, out decimal d);
					return d;

						}

	
	public static DataTreeNode Save(this char value)
	{
					return new DataTreeValue(value);
			}

	public static char LoadChar(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<char>();
						}

	
	public static DataTreeNode Save(this string value)
	{
					return new DataTreeValue(value);
			}

	public static string LoadString(this DataTreeNode node)
	{
							// String needs to check for null, but this always translates into empty string
					var valuenode = node as DataTreeValue;
					if(valuenode.IsNull)
						return null;
					else
						return valuenode.Extract<string>();
						}

	
	public static DataTreeNode Save(this Uri value)
	{
					return new DataTreeValue(value);
			}

	public static Uri LoadUri(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<Uri>();
						}

	
	public static DataTreeNode Save(this bool2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static bool2 LoadBool2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new bool2(((DataTreeValue)list[0]).Extract<bool>(),
((DataTreeValue)list[1]).Extract<bool>()
					);
				}

	
	public static DataTreeNode Save(this byte2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static byte2 LoadByte2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new byte2(((DataTreeValue)list[0]).Extract<byte>(),
((DataTreeValue)list[1]).Extract<byte>()
					);
				}

	
	public static DataTreeNode Save(this ushort2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static ushort2 LoadUshort2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ushort2(((DataTreeValue)list[0]).Extract<ushort>(),
((DataTreeValue)list[1]).Extract<ushort>()
					);
				}

	
	public static DataTreeNode Save(this uint2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static uint2 LoadUint2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new uint2(((DataTreeValue)list[0]).Extract<uint>(),
((DataTreeValue)list[1]).Extract<uint>()
					);
				}

	
	public static DataTreeNode Save(this ulong2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static ulong2 LoadUlong2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ulong2(((DataTreeValue)list[0]).Extract<ulong>(),
((DataTreeValue)list[1]).Extract<ulong>()
					);
				}

	
	public static DataTreeNode Save(this sbyte2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static sbyte2 LoadSbyte2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new sbyte2(((DataTreeValue)list[0]).Extract<sbyte>(),
((DataTreeValue)list[1]).Extract<sbyte>()
					);
				}

	
	public static DataTreeNode Save(this short2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static short2 LoadShort2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new short2(((DataTreeValue)list[0]).Extract<short>(),
((DataTreeValue)list[1]).Extract<short>()
					);
				}

	
	public static DataTreeNode Save(this int2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static int2 LoadInt2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new int2(((DataTreeValue)list[0]).Extract<int>(),
((DataTreeValue)list[1]).Extract<int>()
					);
				}

	
	public static DataTreeNode Save(this long2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static long2 LoadLong2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new long2(((DataTreeValue)list[0]).Extract<long>(),
((DataTreeValue)list[1]).Extract<long>()
					);
				}

	
	public static DataTreeNode Save(this float2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static float2 LoadFloat2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new float2(((DataTreeValue)list[0]).Extract<float>(),
((DataTreeValue)list[1]).Extract<float>()
					);
				}

	
	public static DataTreeNode Save(this double2 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
			
			return listnode;
			}

	public static double2 LoadDouble2(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new double2(((DataTreeValue)list[0]).Extract<double>(),
((DataTreeValue)list[1]).Extract<double>()
					);
				}

	
	public static DataTreeNode Save(this bool3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static bool3 LoadBool3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new bool3(((DataTreeValue)list[0]).Extract<bool>(),
((DataTreeValue)list[1]).Extract<bool>(),
((DataTreeValue)list[2]).Extract<bool>()
					);
				}

	
	public static DataTreeNode Save(this byte3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static byte3 LoadByte3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new byte3(((DataTreeValue)list[0]).Extract<byte>(),
((DataTreeValue)list[1]).Extract<byte>(),
((DataTreeValue)list[2]).Extract<byte>()
					);
				}

	
	public static DataTreeNode Save(this ushort3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static ushort3 LoadUshort3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ushort3(((DataTreeValue)list[0]).Extract<ushort>(),
((DataTreeValue)list[1]).Extract<ushort>(),
((DataTreeValue)list[2]).Extract<ushort>()
					);
				}

	
	public static DataTreeNode Save(this uint3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static uint3 LoadUint3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new uint3(((DataTreeValue)list[0]).Extract<uint>(),
((DataTreeValue)list[1]).Extract<uint>(),
((DataTreeValue)list[2]).Extract<uint>()
					);
				}

	
	public static DataTreeNode Save(this ulong3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static ulong3 LoadUlong3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ulong3(((DataTreeValue)list[0]).Extract<ulong>(),
((DataTreeValue)list[1]).Extract<ulong>(),
((DataTreeValue)list[2]).Extract<ulong>()
					);
				}

	
	public static DataTreeNode Save(this sbyte3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static sbyte3 LoadSbyte3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new sbyte3(((DataTreeValue)list[0]).Extract<sbyte>(),
((DataTreeValue)list[1]).Extract<sbyte>(),
((DataTreeValue)list[2]).Extract<sbyte>()
					);
				}

	
	public static DataTreeNode Save(this short3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static short3 LoadShort3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new short3(((DataTreeValue)list[0]).Extract<short>(),
((DataTreeValue)list[1]).Extract<short>(),
((DataTreeValue)list[2]).Extract<short>()
					);
				}

	
	public static DataTreeNode Save(this int3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static int3 LoadInt3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new int3(((DataTreeValue)list[0]).Extract<int>(),
((DataTreeValue)list[1]).Extract<int>(),
((DataTreeValue)list[2]).Extract<int>()
					);
				}

	
	public static DataTreeNode Save(this long3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static long3 LoadLong3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new long3(((DataTreeValue)list[0]).Extract<long>(),
((DataTreeValue)list[1]).Extract<long>(),
((DataTreeValue)list[2]).Extract<long>()
					);
				}

	
	public static DataTreeNode Save(this float3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static float3 LoadFloat3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new float3(((DataTreeValue)list[0]).Extract<float>(),
((DataTreeValue)list[1]).Extract<float>(),
((DataTreeValue)list[2]).Extract<float>()
					);
				}

	
	public static DataTreeNode Save(this double3 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
			
			return listnode;
			}

	public static double3 LoadDouble3(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new double3(((DataTreeValue)list[0]).Extract<double>(),
((DataTreeValue)list[1]).Extract<double>(),
((DataTreeValue)list[2]).Extract<double>()
					);
				}

	
	public static DataTreeNode Save(this bool4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static bool4 LoadBool4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new bool4(((DataTreeValue)list[0]).Extract<bool>(),
((DataTreeValue)list[1]).Extract<bool>(),
((DataTreeValue)list[2]).Extract<bool>(),
((DataTreeValue)list[3]).Extract<bool>()
					);
				}

	
	public static DataTreeNode Save(this byte4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static byte4 LoadByte4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new byte4(((DataTreeValue)list[0]).Extract<byte>(),
((DataTreeValue)list[1]).Extract<byte>(),
((DataTreeValue)list[2]).Extract<byte>(),
((DataTreeValue)list[3]).Extract<byte>()
					);
				}

	
	public static DataTreeNode Save(this ushort4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static ushort4 LoadUshort4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ushort4(((DataTreeValue)list[0]).Extract<ushort>(),
((DataTreeValue)list[1]).Extract<ushort>(),
((DataTreeValue)list[2]).Extract<ushort>(),
((DataTreeValue)list[3]).Extract<ushort>()
					);
				}

	
	public static DataTreeNode Save(this uint4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static uint4 LoadUint4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new uint4(((DataTreeValue)list[0]).Extract<uint>(),
((DataTreeValue)list[1]).Extract<uint>(),
((DataTreeValue)list[2]).Extract<uint>(),
((DataTreeValue)list[3]).Extract<uint>()
					);
				}

	
	public static DataTreeNode Save(this ulong4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static ulong4 LoadUlong4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new ulong4(((DataTreeValue)list[0]).Extract<ulong>(),
((DataTreeValue)list[1]).Extract<ulong>(),
((DataTreeValue)list[2]).Extract<ulong>(),
((DataTreeValue)list[3]).Extract<ulong>()
					);
				}

	
	public static DataTreeNode Save(this sbyte4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static sbyte4 LoadSbyte4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new sbyte4(((DataTreeValue)list[0]).Extract<sbyte>(),
((DataTreeValue)list[1]).Extract<sbyte>(),
((DataTreeValue)list[2]).Extract<sbyte>(),
((DataTreeValue)list[3]).Extract<sbyte>()
					);
				}

	
	public static DataTreeNode Save(this short4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static short4 LoadShort4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new short4(((DataTreeValue)list[0]).Extract<short>(),
((DataTreeValue)list[1]).Extract<short>(),
((DataTreeValue)list[2]).Extract<short>(),
((DataTreeValue)list[3]).Extract<short>()
					);
				}

	
	public static DataTreeNode Save(this int4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static int4 LoadInt4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new int4(((DataTreeValue)list[0]).Extract<int>(),
((DataTreeValue)list[1]).Extract<int>(),
((DataTreeValue)list[2]).Extract<int>(),
((DataTreeValue)list[3]).Extract<int>()
					);
				}

	
	public static DataTreeNode Save(this long4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static long4 LoadLong4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new long4(((DataTreeValue)list[0]).Extract<long>(),
((DataTreeValue)list[1]).Extract<long>(),
((DataTreeValue)list[2]).Extract<long>(),
((DataTreeValue)list[3]).Extract<long>()
					);
				}

	
	public static DataTreeNode Save(this float4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static float4 LoadFloat4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new float4(((DataTreeValue)list[0]).Extract<float>(),
((DataTreeValue)list[1]).Extract<float>(),
((DataTreeValue)list[2]).Extract<float>(),
((DataTreeValue)list[3]).Extract<float>()
					);
				}

	
	public static DataTreeNode Save(this double4 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static double4 LoadDouble4(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new double4(((DataTreeValue)list[0]).Extract<double>(),
((DataTreeValue)list[1]).Extract<double>(),
((DataTreeValue)list[2]).Extract<double>(),
((DataTreeValue)list[3]).Extract<double>()
					);
				}

	
	public static DataTreeNode Save(this float2x2 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 2; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 2; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static float2x2 LoadFloat2x2(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
					return new float2x2((rownode0[0] as DataTreeValue).Extract<float>(),
							(rownode0[1] as DataTreeValue).Extract<float>(),
							(rownode1[0] as DataTreeValue).Extract<float>(),
							(rownode1[1] as DataTreeValue).Extract<float>());	}

	
	public static DataTreeNode Save(this double2x2 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 2; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 2; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static double2x2 LoadDouble2x2(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
					return new double2x2((rownode0[0] as DataTreeValue).Extract<double>(),
							(rownode0[1] as DataTreeValue).Extract<double>(),
							(rownode1[0] as DataTreeValue).Extract<double>(),
							(rownode1[1] as DataTreeValue).Extract<double>());	}

	
	public static DataTreeNode Save(this float3x3 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 3; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 3; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static float3x3 LoadFloat3x3(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
										var rownode2 = list[2] as DataTreeList;
					return new float3x3((rownode0[0] as DataTreeValue).Extract<float>(),
							(rownode0[1] as DataTreeValue).Extract<float>(),
							(rownode0[2] as DataTreeValue).Extract<float>(),
							(rownode1[0] as DataTreeValue).Extract<float>(),
							(rownode1[1] as DataTreeValue).Extract<float>(),
							(rownode1[2] as DataTreeValue).Extract<float>(),
							(rownode2[0] as DataTreeValue).Extract<float>(),
							(rownode2[1] as DataTreeValue).Extract<float>(),
							(rownode2[2] as DataTreeValue).Extract<float>());	}

	
	public static DataTreeNode Save(this double3x3 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 3; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 3; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static double3x3 LoadDouble3x3(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
										var rownode2 = list[2] as DataTreeList;
					return new double3x3((rownode0[0] as DataTreeValue).Extract<double>(),
							(rownode0[1] as DataTreeValue).Extract<double>(),
							(rownode0[2] as DataTreeValue).Extract<double>(),
							(rownode1[0] as DataTreeValue).Extract<double>(),
							(rownode1[1] as DataTreeValue).Extract<double>(),
							(rownode1[2] as DataTreeValue).Extract<double>(),
							(rownode2[0] as DataTreeValue).Extract<double>(),
							(rownode2[1] as DataTreeValue).Extract<double>(),
							(rownode2[2] as DataTreeValue).Extract<double>());	}

	
	public static DataTreeNode Save(this float4x4 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 4; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 4; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static float4x4 LoadFloat4x4(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
										var rownode2 = list[2] as DataTreeList;
										var rownode3 = list[3] as DataTreeList;
					return new float4x4((rownode0[0] as DataTreeValue).Extract<float>(),
							(rownode0[1] as DataTreeValue).Extract<float>(),
							(rownode0[2] as DataTreeValue).Extract<float>(),
							(rownode0[3] as DataTreeValue).Extract<float>(),
							(rownode1[0] as DataTreeValue).Extract<float>(),
							(rownode1[1] as DataTreeValue).Extract<float>(),
							(rownode1[2] as DataTreeValue).Extract<float>(),
							(rownode1[3] as DataTreeValue).Extract<float>(),
							(rownode2[0] as DataTreeValue).Extract<float>(),
							(rownode2[1] as DataTreeValue).Extract<float>(),
							(rownode2[2] as DataTreeValue).Extract<float>(),
							(rownode2[3] as DataTreeValue).Extract<float>(),
							(rownode3[0] as DataTreeValue).Extract<float>(),
							(rownode3[1] as DataTreeValue).Extract<float>(),
							(rownode3[2] as DataTreeValue).Extract<float>(),
							(rownode3[3] as DataTreeValue).Extract<float>());	}

	
	public static DataTreeNode Save(this double4x4 value)
	{
					var listnode = new DataTreeList();

			for(int r = 0; r < 4; r++)
			{
				var rownode = new DataTreeList();

				for(int c = 0; c < 4; c++)
					rownode.Add(new DataTreeValue(value[r,c]));

				listnode.Add(rownode);
			}

			return listnode;
			}

	public static double4x4 LoadDouble4x4(this DataTreeNode node)
	{
						var list = node as DataTreeList;

									var rownode0 = list[0] as DataTreeList;
										var rownode1 = list[1] as DataTreeList;
										var rownode2 = list[2] as DataTreeList;
										var rownode3 = list[3] as DataTreeList;
					return new double4x4((rownode0[0] as DataTreeValue).Extract<double>(),
							(rownode0[1] as DataTreeValue).Extract<double>(),
							(rownode0[2] as DataTreeValue).Extract<double>(),
							(rownode0[3] as DataTreeValue).Extract<double>(),
							(rownode1[0] as DataTreeValue).Extract<double>(),
							(rownode1[1] as DataTreeValue).Extract<double>(),
							(rownode1[2] as DataTreeValue).Extract<double>(),
							(rownode1[3] as DataTreeValue).Extract<double>(),
							(rownode2[0] as DataTreeValue).Extract<double>(),
							(rownode2[1] as DataTreeValue).Extract<double>(),
							(rownode2[2] as DataTreeValue).Extract<double>(),
							(rownode2[3] as DataTreeValue).Extract<double>(),
							(rownode3[0] as DataTreeValue).Extract<double>(),
							(rownode3[1] as DataTreeValue).Extract<double>(),
							(rownode3[2] as DataTreeValue).Extract<double>(),
							(rownode3[3] as DataTreeValue).Extract<double>());	}

	
	public static DataTreeNode Save(this floatQ value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static floatQ LoadFloatQ(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new floatQ(((DataTreeValue)list[0]).Extract<float>(),
((DataTreeValue)list[1]).Extract<float>(),
((DataTreeValue)list[2]).Extract<float>(),
((DataTreeValue)list[3]).Extract<float>()
					);
				}

	
	public static DataTreeNode Save(this doubleQ value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static doubleQ LoadDoubleQ(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new doubleQ(((DataTreeValue)list[0]).Extract<double>(),
((DataTreeValue)list[1]).Extract<double>(),
((DataTreeValue)list[2]).Extract<double>(),
((DataTreeValue)list[3]).Extract<double>()
					);
				}

	
	public static DataTreeNode Save(this System.DateTime value)
	{
					return new DataTreeValue(value);
			}

	public static System.DateTime LoadDateTime(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<System.DateTime>();
						}

	
	public static DataTreeNode Save(this System.TimeSpan value)
	{
					return new DataTreeValue(value);
			}

	public static System.TimeSpan LoadTimeSpan(this DataTreeNode node)
	{
							return ((DataTreeValue)node).Extract<System.TimeSpan>();
						}

	
	public static DataTreeNode Save(this color value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static color LoadColor(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new color(((DataTreeValue)list[0]).Extract<float>(),
((DataTreeValue)list[1]).Extract<float>(),
((DataTreeValue)list[2]).Extract<float>(),
((DataTreeValue)list[3]).Extract<float>()
					);
				}

	
	public static DataTreeNode Save(this colorX value)
	{
					// we use base serialization of the color and tack in the profile after it for backwards compatibility
			// that way old builds will be able to load the color, even though they loose the color profile information
			var listnode = (DataTreeList)value.baseColor.Save();
			listnode.Add(DataTreeValue.FromEnum(value.profile));
			return listnode;
			}

	public static colorX LoadColorX(this DataTreeNode node)
	{
						var listnode = (DataTreeList)node;
				var baseColor = node.LoadColor();
				var profile = ColorProfile.sRGBAlpha;

				// For backwards compatibility we check if there actually is 5th element in the list which contains the color profile
				// We might be loading value that was original color
				if(listnode.Count > 4)
					profile = ((DataTreeValue)listnode[4]).ExtractEnum<ColorProfile>();

				return new colorX(baseColor, profile);
					}

	
	public static DataTreeNode Save(this color32 value)
	{
					var listnode = new DataTreeList();
							listnode.Add(new DataTreeValue(value[0]));
							listnode.Add(new DataTreeValue(value[1]));
							listnode.Add(new DataTreeValue(value[2]));
							listnode.Add(new DataTreeValue(value[3]));
			
			return listnode;
			}

	public static color32 LoadColor32(this DataTreeNode node)
	{
						var list = (DataTreeList)node;

				// extract the individual elementary values
				return new color32(((DataTreeValue)list[0]).Extract<byte>(),
((DataTreeValue)list[1]).Extract<byte>(),
((DataTreeValue)list[2]).Extract<byte>(),
((DataTreeValue)list[3]).Extract<byte>()
					);
				}

	
}

} // namespace FrooxEngine
