// Autogenerated!!! DO NOT MODIFY!
// Generated on: 03/10/2026 22:59:53

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Elements.Data;

namespace Elements.Core;


    [DataModelType]
    public struct SphericalHarmonicsL1<T> : ISphericalHarmonics<T>,
        IEncodable, IEquatable<SphericalHarmonicsL1<T>>,
        IAddable<SphericalHarmonicsL1<T>>,
        ISubtractable<SphericalHarmonicsL1<T>>,
        IScalable<SphericalHarmonicsL1<T>>,
        ILerpable<SphericalHarmonicsL1<T>>
        where T : unmanaged, IEquatable<T>
    {
        public const int COEFFICIENT_COUNT = 4;

        public static bool IsValidGenericType
        {
            get
            {
                unsafe
                {
                    return (sizeof(T) * COEFFICIENT_COUNT) <= ReflectionExtensions.MAX_VALUE_SIZE;
                }
            }
        }

        [JsonIgnore]
        public int Order => 1;

        [JsonIgnore]
        public int CoefficientCount => COEFFICIENT_COUNT;

        [JsonIgnore]
        public Type CoefficientType => typeof(T);

        [JsonInclude]
        public T sh0, sh1, sh2, sh3;

        [JsonIgnore]
        public T this[int index]
        {
            get
            {
                switch (index)
                {
                                             case 0: return sh0;
                                                 case 1: return sh1;
                                                 case 2: return sh2;
                                                 case 3: return sh3;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }

            set
            {
                switch (index)
                {
                                             case 0: sh0 = value; break;
                                                 case 1: sh1 = value; break;
                                                 case 2: sh2 = value; break;
                                                 case 3: sh3 = value; break;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }
        }

        [JsonIgnore]
        public bool IsValid =>
            Coder<T>.IsValid(sh0) &&
	Coder<T>.IsValid(sh1) &&
	Coder<T>.IsValid(sh2) &&
	Coder<T>.IsValid(sh3);

        public SphericalHarmonicsL1(T sh0, T sh1, T sh2, T sh3)
        {
                            this.sh0 = sh0;
                                this.sh1 = sh1;
                                this.sh2 = sh2;
                                this.sh3 = sh3;
                        }

        public void Encode(BinaryWriter writer)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                Coder<T>.Encode(this[i], writer);
        }

        public DataTreeNode Save()
        {
            var coeffNames = new DataTreeList();

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                coeffNames.Add(Coder<T>.Save(this[i]));

            return coeffNames;
        }

        public void Load(DataTreeNode node)
        {
            var coeffNames = (DataTreeList)node;

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Load(coeffNames[i]);
        }

        public void Decode(BinaryReader reader)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Decode(reader);
        }

        public override string ToString() => this.FormatToString();

        public SphericalHarmonicsL1<O> Convert<O>(Func<T,O> conversion)
            where O : unmanaged, IEquatable<O>
        {
            return new SphericalHarmonicsL1<O>(
                conversion(sh0),
conversion(sh1),
conversion(sh2),
conversion(sh3)
            );
        }

        #region INTERFACE OPERATIONS

        public SphericalHarmonicsL1<T> Add(SphericalHarmonicsL1<T> other) => this + other;
        public SphericalHarmonicsL1<T> Sub(SphericalHarmonicsL1<T> other) => this - other;
        public SphericalHarmonicsL1<T> Scale(float n) => this * n;
        public SphericalHarmonicsL1<T> LerpUnclamped(SphericalHarmonicsL1<T> other, float lerp) => MathX.LerpUnclamped(this, other, lerp);
        public SphericalHarmonicsL1<T> Lerp(SphericalHarmonicsL1<T> other, float lerp) => MathX.Lerp(this, other, lerp);
        public SphericalHarmonicsL1<T> ConstantLerp(SphericalHarmonicsL1<T> other, float delta) => MathX.ConstantLerp(this, other, delta);
        public SphericalHarmonicsL1<T> SmoothLerp(SphericalHarmonicsL1<T> other,
            ref SphericalHarmonicsL1<T> intermediate, float delta) => MathX.SmoothLerp(this, other, ref intermediate, delta);

        #endregion 

        #region OPERATORS

        public override bool Equals(object obj)
        {
            if (obj is SphericalHarmonicsL1<T> sh)
                return Equals(sh);

            return false;
        }

        public bool Equals(SphericalHarmonicsL1<T> other)
        {
            return sh0.Equals(other.sh0) && 
   sh1.Equals(other.sh1) && 
   sh2.Equals(other.sh2) && 
   sh3.Equals(other.sh3);
        }

        public override int GetHashCode()
        {
            int hashCode = 412434100;
                            hashCode = hashCode * -1521134295 + sh0.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh1.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh2.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh3.GetHashCode();
                            return hashCode;
        }

        public static bool operator ==(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b)
            => a.Equals(b);

        public static bool operator !=(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b)
            => !a.Equals(b);

        public static SphericalHarmonicsL1<T> operator +(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b)
        {
            return new SphericalHarmonicsL1<T>
            (
                Coder<T>.Add(a.sh0, b.sh0),
Coder<T>.Add(a.sh1, b.sh1),
Coder<T>.Add(a.sh2, b.sh2),
Coder<T>.Add(a.sh3, b.sh3)
            );
        }

        public static SphericalHarmonicsL1<T> operator -(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b)
        {
            return new SphericalHarmonicsL1<T>
            (
                Coder<T>.Sub(a.sh0, b.sh0),
Coder<T>.Sub(a.sh1, b.sh1),
Coder<T>.Sub(a.sh2, b.sh2),
Coder<T>.Sub(a.sh3, b.sh3)
            );
        }

        public static SphericalHarmonicsL1<T> operator *(SphericalHarmonicsL1<T> sh, float n)
        {
            return new SphericalHarmonicsL1<T>
            (
                Coder<T>.Scale(sh.sh0, n),
Coder<T>.Scale(sh.sh1, n),
Coder<T>.Scale(sh.sh2, n),
Coder<T>.Scale(sh.sh3, n)
            );
        }

        public static SphericalHarmonicsL1<T> operator *(float n, SphericalHarmonicsL1<T> sh) => sh * n;

        public SphericalHarmonicsL1<T> ScaleOrders( float order0, float order1 )
        {
            return new SphericalHarmonicsL1<T>(
                Coder<T>.Scale(sh0, order0),
Coder<T>.Scale(sh1, order1),
Coder<T>.Scale(sh2, order1),
Coder<T>.Scale(sh3, order1)
                );
        }

        #endregion
    }

    public static partial class MathX
    {
        public static SphericalHarmonicsL1<T> Lerp<T>(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            if(lerp <= 0f)
                return a;

            if(lerp >= 1f)
                return b;

            return LerpUnclamped(a, b, lerp);
        }

        public static SphericalHarmonicsL1<T> LerpUnclamped<T>(SphericalHarmonicsL1<T> a, SphericalHarmonicsL1<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            return a + (b - a) * lerp;
        }

        public static SphericalHarmonicsL1<T> ConstantLerp<T>(SphericalHarmonicsL1<T> current, SphericalHarmonicsL1<T> target, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL1<T>(
                Coder<T>.ConstantLerp(current.sh0, target.sh0, delta),
Coder<T>.ConstantLerp(current.sh1, target.sh1, delta),
Coder<T>.ConstantLerp(current.sh2, target.sh2, delta),
Coder<T>.ConstantLerp(current.sh3, target.sh3, delta));
        }

        public static SphericalHarmonicsL1<T> SmoothLerp<T>(SphericalHarmonicsL1<T> current,
            SphericalHarmonicsL1<T> target,
            ref SphericalHarmonicsL1<T> intermediate, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL1<T>(
                Coder<T>.SmoothLerp(current.sh0, target.sh0, ref intermediate.sh0, delta),
Coder<T>.SmoothLerp(current.sh1, target.sh1, ref intermediate.sh1, delta),
Coder<T>.SmoothLerp(current.sh2, target.sh2, ref intermediate.sh2, delta),
Coder<T>.SmoothLerp(current.sh3, target.sh3, ref intermediate.sh3, delta));
        }
    }
    
    [DataModelType]
    public struct SphericalHarmonicsL2<T> : ISphericalHarmonics<T>,
        IEncodable, IEquatable<SphericalHarmonicsL2<T>>,
        IAddable<SphericalHarmonicsL2<T>>,
        ISubtractable<SphericalHarmonicsL2<T>>,
        IScalable<SphericalHarmonicsL2<T>>,
        ILerpable<SphericalHarmonicsL2<T>>
        where T : unmanaged, IEquatable<T>
    {
        public const int COEFFICIENT_COUNT = 9;

        public static bool IsValidGenericType
        {
            get
            {
                unsafe
                {
                    return (sizeof(T) * COEFFICIENT_COUNT) <= ReflectionExtensions.MAX_VALUE_SIZE;
                }
            }
        }

        [JsonIgnore]
        public int Order => 2;

        [JsonIgnore]
        public int CoefficientCount => COEFFICIENT_COUNT;

        [JsonIgnore]
        public Type CoefficientType => typeof(T);

        [JsonInclude]
        public T sh0, sh1, sh2, sh3, sh4, sh5, sh6, sh7, sh8;

        [JsonIgnore]
        public T this[int index]
        {
            get
            {
                switch (index)
                {
                                             case 0: return sh0;
                                                 case 1: return sh1;
                                                 case 2: return sh2;
                                                 case 3: return sh3;
                                                 case 4: return sh4;
                                                 case 5: return sh5;
                                                 case 6: return sh6;
                                                 case 7: return sh7;
                                                 case 8: return sh8;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }

            set
            {
                switch (index)
                {
                                             case 0: sh0 = value; break;
                                                 case 1: sh1 = value; break;
                                                 case 2: sh2 = value; break;
                                                 case 3: sh3 = value; break;
                                                 case 4: sh4 = value; break;
                                                 case 5: sh5 = value; break;
                                                 case 6: sh6 = value; break;
                                                 case 7: sh7 = value; break;
                                                 case 8: sh8 = value; break;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }
        }

        [JsonIgnore]
        public bool IsValid =>
            Coder<T>.IsValid(sh0) &&
	Coder<T>.IsValid(sh1) &&
	Coder<T>.IsValid(sh2) &&
	Coder<T>.IsValid(sh3) &&
	Coder<T>.IsValid(sh4) &&
	Coder<T>.IsValid(sh5) &&
	Coder<T>.IsValid(sh6) &&
	Coder<T>.IsValid(sh7) &&
	Coder<T>.IsValid(sh8);

        public SphericalHarmonicsL2(T sh0, T sh1, T sh2, T sh3, T sh4, T sh5, T sh6, T sh7, T sh8)
        {
                            this.sh0 = sh0;
                                this.sh1 = sh1;
                                this.sh2 = sh2;
                                this.sh3 = sh3;
                                this.sh4 = sh4;
                                this.sh5 = sh5;
                                this.sh6 = sh6;
                                this.sh7 = sh7;
                                this.sh8 = sh8;
                        }

        public void Encode(BinaryWriter writer)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                Coder<T>.Encode(this[i], writer);
        }

        public DataTreeNode Save()
        {
            var coeffNames = new DataTreeList();

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                coeffNames.Add(Coder<T>.Save(this[i]));

            return coeffNames;
        }

        public void Load(DataTreeNode node)
        {
            var coeffNames = (DataTreeList)node;

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Load(coeffNames[i]);
        }

        public void Decode(BinaryReader reader)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Decode(reader);
        }

        public override string ToString() => this.FormatToString();

        public SphericalHarmonicsL2<O> Convert<O>(Func<T,O> conversion)
            where O : unmanaged, IEquatable<O>
        {
            return new SphericalHarmonicsL2<O>(
                conversion(sh0),
conversion(sh1),
conversion(sh2),
conversion(sh3),
conversion(sh4),
conversion(sh5),
conversion(sh6),
conversion(sh7),
conversion(sh8)
            );
        }

        #region INTERFACE OPERATIONS

        public SphericalHarmonicsL2<T> Add(SphericalHarmonicsL2<T> other) => this + other;
        public SphericalHarmonicsL2<T> Sub(SphericalHarmonicsL2<T> other) => this - other;
        public SphericalHarmonicsL2<T> Scale(float n) => this * n;
        public SphericalHarmonicsL2<T> LerpUnclamped(SphericalHarmonicsL2<T> other, float lerp) => MathX.LerpUnclamped(this, other, lerp);
        public SphericalHarmonicsL2<T> Lerp(SphericalHarmonicsL2<T> other, float lerp) => MathX.Lerp(this, other, lerp);
        public SphericalHarmonicsL2<T> ConstantLerp(SphericalHarmonicsL2<T> other, float delta) => MathX.ConstantLerp(this, other, delta);
        public SphericalHarmonicsL2<T> SmoothLerp(SphericalHarmonicsL2<T> other,
            ref SphericalHarmonicsL2<T> intermediate, float delta) => MathX.SmoothLerp(this, other, ref intermediate, delta);

        #endregion 

        #region OPERATORS

        public override bool Equals(object obj)
        {
            if (obj is SphericalHarmonicsL2<T> sh)
                return Equals(sh);

            return false;
        }

        public bool Equals(SphericalHarmonicsL2<T> other)
        {
            return sh0.Equals(other.sh0) && 
   sh1.Equals(other.sh1) && 
   sh2.Equals(other.sh2) && 
   sh3.Equals(other.sh3) && 
   sh4.Equals(other.sh4) && 
   sh5.Equals(other.sh5) && 
   sh6.Equals(other.sh6) && 
   sh7.Equals(other.sh7) && 
   sh8.Equals(other.sh8);
        }

        public override int GetHashCode()
        {
            int hashCode = 412434100;
                            hashCode = hashCode * -1521134295 + sh0.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh1.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh2.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh3.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh4.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh5.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh6.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh7.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh8.GetHashCode();
                            return hashCode;
        }

        public static bool operator ==(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b)
            => a.Equals(b);

        public static bool operator !=(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b)
            => !a.Equals(b);

        public static SphericalHarmonicsL2<T> operator +(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b)
        {
            return new SphericalHarmonicsL2<T>
            (
                Coder<T>.Add(a.sh0, b.sh0),
Coder<T>.Add(a.sh1, b.sh1),
Coder<T>.Add(a.sh2, b.sh2),
Coder<T>.Add(a.sh3, b.sh3),
Coder<T>.Add(a.sh4, b.sh4),
Coder<T>.Add(a.sh5, b.sh5),
Coder<T>.Add(a.sh6, b.sh6),
Coder<T>.Add(a.sh7, b.sh7),
Coder<T>.Add(a.sh8, b.sh8)
            );
        }

        public static SphericalHarmonicsL2<T> operator -(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b)
        {
            return new SphericalHarmonicsL2<T>
            (
                Coder<T>.Sub(a.sh0, b.sh0),
Coder<T>.Sub(a.sh1, b.sh1),
Coder<T>.Sub(a.sh2, b.sh2),
Coder<T>.Sub(a.sh3, b.sh3),
Coder<T>.Sub(a.sh4, b.sh4),
Coder<T>.Sub(a.sh5, b.sh5),
Coder<T>.Sub(a.sh6, b.sh6),
Coder<T>.Sub(a.sh7, b.sh7),
Coder<T>.Sub(a.sh8, b.sh8)
            );
        }

        public static SphericalHarmonicsL2<T> operator *(SphericalHarmonicsL2<T> sh, float n)
        {
            return new SphericalHarmonicsL2<T>
            (
                Coder<T>.Scale(sh.sh0, n),
Coder<T>.Scale(sh.sh1, n),
Coder<T>.Scale(sh.sh2, n),
Coder<T>.Scale(sh.sh3, n),
Coder<T>.Scale(sh.sh4, n),
Coder<T>.Scale(sh.sh5, n),
Coder<T>.Scale(sh.sh6, n),
Coder<T>.Scale(sh.sh7, n),
Coder<T>.Scale(sh.sh8, n)
            );
        }

        public static SphericalHarmonicsL2<T> operator *(float n, SphericalHarmonicsL2<T> sh) => sh * n;

        public SphericalHarmonicsL2<T> ScaleOrders( float order0, float order1, float order2 )
        {
            return new SphericalHarmonicsL2<T>(
                Coder<T>.Scale(sh0, order0),
Coder<T>.Scale(sh1, order1),
Coder<T>.Scale(sh2, order1),
Coder<T>.Scale(sh3, order1),
Coder<T>.Scale(sh4, order2),
Coder<T>.Scale(sh5, order2),
Coder<T>.Scale(sh6, order2),
Coder<T>.Scale(sh7, order2),
Coder<T>.Scale(sh8, order2)
                );
        }

        #endregion
    }

    public static partial class MathX
    {
        public static SphericalHarmonicsL2<T> Lerp<T>(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            if(lerp <= 0f)
                return a;

            if(lerp >= 1f)
                return b;

            return LerpUnclamped(a, b, lerp);
        }

        public static SphericalHarmonicsL2<T> LerpUnclamped<T>(SphericalHarmonicsL2<T> a, SphericalHarmonicsL2<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            return a + (b - a) * lerp;
        }

        public static SphericalHarmonicsL2<T> ConstantLerp<T>(SphericalHarmonicsL2<T> current, SphericalHarmonicsL2<T> target, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL2<T>(
                Coder<T>.ConstantLerp(current.sh0, target.sh0, delta),
Coder<T>.ConstantLerp(current.sh1, target.sh1, delta),
Coder<T>.ConstantLerp(current.sh2, target.sh2, delta),
Coder<T>.ConstantLerp(current.sh3, target.sh3, delta),
Coder<T>.ConstantLerp(current.sh4, target.sh4, delta),
Coder<T>.ConstantLerp(current.sh5, target.sh5, delta),
Coder<T>.ConstantLerp(current.sh6, target.sh6, delta),
Coder<T>.ConstantLerp(current.sh7, target.sh7, delta),
Coder<T>.ConstantLerp(current.sh8, target.sh8, delta));
        }

        public static SphericalHarmonicsL2<T> SmoothLerp<T>(SphericalHarmonicsL2<T> current,
            SphericalHarmonicsL2<T> target,
            ref SphericalHarmonicsL2<T> intermediate, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL2<T>(
                Coder<T>.SmoothLerp(current.sh0, target.sh0, ref intermediate.sh0, delta),
Coder<T>.SmoothLerp(current.sh1, target.sh1, ref intermediate.sh1, delta),
Coder<T>.SmoothLerp(current.sh2, target.sh2, ref intermediate.sh2, delta),
Coder<T>.SmoothLerp(current.sh3, target.sh3, ref intermediate.sh3, delta),
Coder<T>.SmoothLerp(current.sh4, target.sh4, ref intermediate.sh4, delta),
Coder<T>.SmoothLerp(current.sh5, target.sh5, ref intermediate.sh5, delta),
Coder<T>.SmoothLerp(current.sh6, target.sh6, ref intermediate.sh6, delta),
Coder<T>.SmoothLerp(current.sh7, target.sh7, ref intermediate.sh7, delta),
Coder<T>.SmoothLerp(current.sh8, target.sh8, ref intermediate.sh8, delta));
        }
    }
    
    [DataModelType]
    public struct SphericalHarmonicsL3<T> : ISphericalHarmonics<T>,
        IEncodable, IEquatable<SphericalHarmonicsL3<T>>,
        IAddable<SphericalHarmonicsL3<T>>,
        ISubtractable<SphericalHarmonicsL3<T>>,
        IScalable<SphericalHarmonicsL3<T>>,
        ILerpable<SphericalHarmonicsL3<T>>
        where T : unmanaged, IEquatable<T>
    {
        public const int COEFFICIENT_COUNT = 16;

        public static bool IsValidGenericType
        {
            get
            {
                unsafe
                {
                    return (sizeof(T) * COEFFICIENT_COUNT) <= ReflectionExtensions.MAX_VALUE_SIZE;
                }
            }
        }

        [JsonIgnore]
        public int Order => 3;

        [JsonIgnore]
        public int CoefficientCount => COEFFICIENT_COUNT;

        [JsonIgnore]
        public Type CoefficientType => typeof(T);

        [JsonInclude]
        public T sh0, sh1, sh2, sh3, sh4, sh5, sh6, sh7, sh8, sh9, sh10, sh11, sh12, sh13, sh14, sh15;

        [JsonIgnore]
        public T this[int index]
        {
            get
            {
                switch (index)
                {
                                             case 0: return sh0;
                                                 case 1: return sh1;
                                                 case 2: return sh2;
                                                 case 3: return sh3;
                                                 case 4: return sh4;
                                                 case 5: return sh5;
                                                 case 6: return sh6;
                                                 case 7: return sh7;
                                                 case 8: return sh8;
                                                 case 9: return sh9;
                                                 case 10: return sh10;
                                                 case 11: return sh11;
                                                 case 12: return sh12;
                                                 case 13: return sh13;
                                                 case 14: return sh14;
                                                 case 15: return sh15;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }

            set
            {
                switch (index)
                {
                                             case 0: sh0 = value; break;
                                                 case 1: sh1 = value; break;
                                                 case 2: sh2 = value; break;
                                                 case 3: sh3 = value; break;
                                                 case 4: sh4 = value; break;
                                                 case 5: sh5 = value; break;
                                                 case 6: sh6 = value; break;
                                                 case 7: sh7 = value; break;
                                                 case 8: sh8 = value; break;
                                                 case 9: sh9 = value; break;
                                                 case 10: sh10 = value; break;
                                                 case 11: sh11 = value; break;
                                                 case 12: sh12 = value; break;
                                                 case 13: sh13 = value; break;
                                                 case 14: sh14 = value; break;
                                                 case 15: sh15 = value; break;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }
        }

        [JsonIgnore]
        public bool IsValid =>
            Coder<T>.IsValid(sh0) &&
	Coder<T>.IsValid(sh1) &&
	Coder<T>.IsValid(sh2) &&
	Coder<T>.IsValid(sh3) &&
	Coder<T>.IsValid(sh4) &&
	Coder<T>.IsValid(sh5) &&
	Coder<T>.IsValid(sh6) &&
	Coder<T>.IsValid(sh7) &&
	Coder<T>.IsValid(sh8) &&
	Coder<T>.IsValid(sh9) &&
	Coder<T>.IsValid(sh10) &&
	Coder<T>.IsValid(sh11) &&
	Coder<T>.IsValid(sh12) &&
	Coder<T>.IsValid(sh13) &&
	Coder<T>.IsValid(sh14) &&
	Coder<T>.IsValid(sh15);

        public SphericalHarmonicsL3(T sh0, T sh1, T sh2, T sh3, T sh4, T sh5, T sh6, T sh7, T sh8, T sh9, T sh10, T sh11, T sh12, T sh13, T sh14, T sh15)
        {
                            this.sh0 = sh0;
                                this.sh1 = sh1;
                                this.sh2 = sh2;
                                this.sh3 = sh3;
                                this.sh4 = sh4;
                                this.sh5 = sh5;
                                this.sh6 = sh6;
                                this.sh7 = sh7;
                                this.sh8 = sh8;
                                this.sh9 = sh9;
                                this.sh10 = sh10;
                                this.sh11 = sh11;
                                this.sh12 = sh12;
                                this.sh13 = sh13;
                                this.sh14 = sh14;
                                this.sh15 = sh15;
                        }

        public void Encode(BinaryWriter writer)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                Coder<T>.Encode(this[i], writer);
        }

        public DataTreeNode Save()
        {
            var coeffNames = new DataTreeList();

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                coeffNames.Add(Coder<T>.Save(this[i]));

            return coeffNames;
        }

        public void Load(DataTreeNode node)
        {
            var coeffNames = (DataTreeList)node;

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Load(coeffNames[i]);
        }

        public void Decode(BinaryReader reader)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Decode(reader);
        }

        public override string ToString() => this.FormatToString();

        public SphericalHarmonicsL3<O> Convert<O>(Func<T,O> conversion)
            where O : unmanaged, IEquatable<O>
        {
            return new SphericalHarmonicsL3<O>(
                conversion(sh0),
conversion(sh1),
conversion(sh2),
conversion(sh3),
conversion(sh4),
conversion(sh5),
conversion(sh6),
conversion(sh7),
conversion(sh8),
conversion(sh9),
conversion(sh10),
conversion(sh11),
conversion(sh12),
conversion(sh13),
conversion(sh14),
conversion(sh15)
            );
        }

        #region INTERFACE OPERATIONS

        public SphericalHarmonicsL3<T> Add(SphericalHarmonicsL3<T> other) => this + other;
        public SphericalHarmonicsL3<T> Sub(SphericalHarmonicsL3<T> other) => this - other;
        public SphericalHarmonicsL3<T> Scale(float n) => this * n;
        public SphericalHarmonicsL3<T> LerpUnclamped(SphericalHarmonicsL3<T> other, float lerp) => MathX.LerpUnclamped(this, other, lerp);
        public SphericalHarmonicsL3<T> Lerp(SphericalHarmonicsL3<T> other, float lerp) => MathX.Lerp(this, other, lerp);
        public SphericalHarmonicsL3<T> ConstantLerp(SphericalHarmonicsL3<T> other, float delta) => MathX.ConstantLerp(this, other, delta);
        public SphericalHarmonicsL3<T> SmoothLerp(SphericalHarmonicsL3<T> other,
            ref SphericalHarmonicsL3<T> intermediate, float delta) => MathX.SmoothLerp(this, other, ref intermediate, delta);

        #endregion 

        #region OPERATORS

        public override bool Equals(object obj)
        {
            if (obj is SphericalHarmonicsL3<T> sh)
                return Equals(sh);

            return false;
        }

        public bool Equals(SphericalHarmonicsL3<T> other)
        {
            return sh0.Equals(other.sh0) && 
   sh1.Equals(other.sh1) && 
   sh2.Equals(other.sh2) && 
   sh3.Equals(other.sh3) && 
   sh4.Equals(other.sh4) && 
   sh5.Equals(other.sh5) && 
   sh6.Equals(other.sh6) && 
   sh7.Equals(other.sh7) && 
   sh8.Equals(other.sh8) && 
   sh9.Equals(other.sh9) && 
   sh10.Equals(other.sh10) && 
   sh11.Equals(other.sh11) && 
   sh12.Equals(other.sh12) && 
   sh13.Equals(other.sh13) && 
   sh14.Equals(other.sh14) && 
   sh15.Equals(other.sh15);
        }

        public override int GetHashCode()
        {
            int hashCode = 412434100;
                            hashCode = hashCode * -1521134295 + sh0.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh1.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh2.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh3.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh4.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh5.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh6.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh7.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh8.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh9.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh10.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh11.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh12.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh13.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh14.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh15.GetHashCode();
                            return hashCode;
        }

        public static bool operator ==(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b)
            => a.Equals(b);

        public static bool operator !=(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b)
            => !a.Equals(b);

        public static SphericalHarmonicsL3<T> operator +(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b)
        {
            return new SphericalHarmonicsL3<T>
            (
                Coder<T>.Add(a.sh0, b.sh0),
Coder<T>.Add(a.sh1, b.sh1),
Coder<T>.Add(a.sh2, b.sh2),
Coder<T>.Add(a.sh3, b.sh3),
Coder<T>.Add(a.sh4, b.sh4),
Coder<T>.Add(a.sh5, b.sh5),
Coder<T>.Add(a.sh6, b.sh6),
Coder<T>.Add(a.sh7, b.sh7),
Coder<T>.Add(a.sh8, b.sh8),
Coder<T>.Add(a.sh9, b.sh9),
Coder<T>.Add(a.sh10, b.sh10),
Coder<T>.Add(a.sh11, b.sh11),
Coder<T>.Add(a.sh12, b.sh12),
Coder<T>.Add(a.sh13, b.sh13),
Coder<T>.Add(a.sh14, b.sh14),
Coder<T>.Add(a.sh15, b.sh15)
            );
        }

        public static SphericalHarmonicsL3<T> operator -(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b)
        {
            return new SphericalHarmonicsL3<T>
            (
                Coder<T>.Sub(a.sh0, b.sh0),
Coder<T>.Sub(a.sh1, b.sh1),
Coder<T>.Sub(a.sh2, b.sh2),
Coder<T>.Sub(a.sh3, b.sh3),
Coder<T>.Sub(a.sh4, b.sh4),
Coder<T>.Sub(a.sh5, b.sh5),
Coder<T>.Sub(a.sh6, b.sh6),
Coder<T>.Sub(a.sh7, b.sh7),
Coder<T>.Sub(a.sh8, b.sh8),
Coder<T>.Sub(a.sh9, b.sh9),
Coder<T>.Sub(a.sh10, b.sh10),
Coder<T>.Sub(a.sh11, b.sh11),
Coder<T>.Sub(a.sh12, b.sh12),
Coder<T>.Sub(a.sh13, b.sh13),
Coder<T>.Sub(a.sh14, b.sh14),
Coder<T>.Sub(a.sh15, b.sh15)
            );
        }

        public static SphericalHarmonicsL3<T> operator *(SphericalHarmonicsL3<T> sh, float n)
        {
            return new SphericalHarmonicsL3<T>
            (
                Coder<T>.Scale(sh.sh0, n),
Coder<T>.Scale(sh.sh1, n),
Coder<T>.Scale(sh.sh2, n),
Coder<T>.Scale(sh.sh3, n),
Coder<T>.Scale(sh.sh4, n),
Coder<T>.Scale(sh.sh5, n),
Coder<T>.Scale(sh.sh6, n),
Coder<T>.Scale(sh.sh7, n),
Coder<T>.Scale(sh.sh8, n),
Coder<T>.Scale(sh.sh9, n),
Coder<T>.Scale(sh.sh10, n),
Coder<T>.Scale(sh.sh11, n),
Coder<T>.Scale(sh.sh12, n),
Coder<T>.Scale(sh.sh13, n),
Coder<T>.Scale(sh.sh14, n),
Coder<T>.Scale(sh.sh15, n)
            );
        }

        public static SphericalHarmonicsL3<T> operator *(float n, SphericalHarmonicsL3<T> sh) => sh * n;

        public SphericalHarmonicsL3<T> ScaleOrders( float order0, float order1, float order2, float order3 )
        {
            return new SphericalHarmonicsL3<T>(
                Coder<T>.Scale(sh0, order0),
Coder<T>.Scale(sh1, order1),
Coder<T>.Scale(sh2, order1),
Coder<T>.Scale(sh3, order1),
Coder<T>.Scale(sh4, order2),
Coder<T>.Scale(sh5, order2),
Coder<T>.Scale(sh6, order2),
Coder<T>.Scale(sh7, order2),
Coder<T>.Scale(sh8, order2),
Coder<T>.Scale(sh9, order3),
Coder<T>.Scale(sh10, order3),
Coder<T>.Scale(sh11, order3),
Coder<T>.Scale(sh12, order3),
Coder<T>.Scale(sh13, order3),
Coder<T>.Scale(sh14, order3),
Coder<T>.Scale(sh15, order3)
                );
        }

        #endregion
    }

    public static partial class MathX
    {
        public static SphericalHarmonicsL3<T> Lerp<T>(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            if(lerp <= 0f)
                return a;

            if(lerp >= 1f)
                return b;

            return LerpUnclamped(a, b, lerp);
        }

        public static SphericalHarmonicsL3<T> LerpUnclamped<T>(SphericalHarmonicsL3<T> a, SphericalHarmonicsL3<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            return a + (b - a) * lerp;
        }

        public static SphericalHarmonicsL3<T> ConstantLerp<T>(SphericalHarmonicsL3<T> current, SphericalHarmonicsL3<T> target, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL3<T>(
                Coder<T>.ConstantLerp(current.sh0, target.sh0, delta),
Coder<T>.ConstantLerp(current.sh1, target.sh1, delta),
Coder<T>.ConstantLerp(current.sh2, target.sh2, delta),
Coder<T>.ConstantLerp(current.sh3, target.sh3, delta),
Coder<T>.ConstantLerp(current.sh4, target.sh4, delta),
Coder<T>.ConstantLerp(current.sh5, target.sh5, delta),
Coder<T>.ConstantLerp(current.sh6, target.sh6, delta),
Coder<T>.ConstantLerp(current.sh7, target.sh7, delta),
Coder<T>.ConstantLerp(current.sh8, target.sh8, delta),
Coder<T>.ConstantLerp(current.sh9, target.sh9, delta),
Coder<T>.ConstantLerp(current.sh10, target.sh10, delta),
Coder<T>.ConstantLerp(current.sh11, target.sh11, delta),
Coder<T>.ConstantLerp(current.sh12, target.sh12, delta),
Coder<T>.ConstantLerp(current.sh13, target.sh13, delta),
Coder<T>.ConstantLerp(current.sh14, target.sh14, delta),
Coder<T>.ConstantLerp(current.sh15, target.sh15, delta));
        }

        public static SphericalHarmonicsL3<T> SmoothLerp<T>(SphericalHarmonicsL3<T> current,
            SphericalHarmonicsL3<T> target,
            ref SphericalHarmonicsL3<T> intermediate, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL3<T>(
                Coder<T>.SmoothLerp(current.sh0, target.sh0, ref intermediate.sh0, delta),
Coder<T>.SmoothLerp(current.sh1, target.sh1, ref intermediate.sh1, delta),
Coder<T>.SmoothLerp(current.sh2, target.sh2, ref intermediate.sh2, delta),
Coder<T>.SmoothLerp(current.sh3, target.sh3, ref intermediate.sh3, delta),
Coder<T>.SmoothLerp(current.sh4, target.sh4, ref intermediate.sh4, delta),
Coder<T>.SmoothLerp(current.sh5, target.sh5, ref intermediate.sh5, delta),
Coder<T>.SmoothLerp(current.sh6, target.sh6, ref intermediate.sh6, delta),
Coder<T>.SmoothLerp(current.sh7, target.sh7, ref intermediate.sh7, delta),
Coder<T>.SmoothLerp(current.sh8, target.sh8, ref intermediate.sh8, delta),
Coder<T>.SmoothLerp(current.sh9, target.sh9, ref intermediate.sh9, delta),
Coder<T>.SmoothLerp(current.sh10, target.sh10, ref intermediate.sh10, delta),
Coder<T>.SmoothLerp(current.sh11, target.sh11, ref intermediate.sh11, delta),
Coder<T>.SmoothLerp(current.sh12, target.sh12, ref intermediate.sh12, delta),
Coder<T>.SmoothLerp(current.sh13, target.sh13, ref intermediate.sh13, delta),
Coder<T>.SmoothLerp(current.sh14, target.sh14, ref intermediate.sh14, delta),
Coder<T>.SmoothLerp(current.sh15, target.sh15, ref intermediate.sh15, delta));
        }
    }
    
    [DataModelType]
    public struct SphericalHarmonicsL4<T> : ISphericalHarmonics<T>,
        IEncodable, IEquatable<SphericalHarmonicsL4<T>>,
        IAddable<SphericalHarmonicsL4<T>>,
        ISubtractable<SphericalHarmonicsL4<T>>,
        IScalable<SphericalHarmonicsL4<T>>,
        ILerpable<SphericalHarmonicsL4<T>>
        where T : unmanaged, IEquatable<T>
    {
        public const int COEFFICIENT_COUNT = 25;

        public static bool IsValidGenericType
        {
            get
            {
                unsafe
                {
                    return (sizeof(T) * COEFFICIENT_COUNT) <= ReflectionExtensions.MAX_VALUE_SIZE;
                }
            }
        }

        [JsonIgnore]
        public int Order => 4;

        [JsonIgnore]
        public int CoefficientCount => COEFFICIENT_COUNT;

        [JsonIgnore]
        public Type CoefficientType => typeof(T);

        [JsonInclude]
        public T sh0, sh1, sh2, sh3, sh4, sh5, sh6, sh7, sh8, sh9, sh10, sh11, sh12, sh13, sh14, sh15, sh16, sh17, sh18, sh19, sh20, sh21, sh22, sh23, sh24;

        [JsonIgnore]
        public T this[int index]
        {
            get
            {
                switch (index)
                {
                                             case 0: return sh0;
                                                 case 1: return sh1;
                                                 case 2: return sh2;
                                                 case 3: return sh3;
                                                 case 4: return sh4;
                                                 case 5: return sh5;
                                                 case 6: return sh6;
                                                 case 7: return sh7;
                                                 case 8: return sh8;
                                                 case 9: return sh9;
                                                 case 10: return sh10;
                                                 case 11: return sh11;
                                                 case 12: return sh12;
                                                 case 13: return sh13;
                                                 case 14: return sh14;
                                                 case 15: return sh15;
                                                 case 16: return sh16;
                                                 case 17: return sh17;
                                                 case 18: return sh18;
                                                 case 19: return sh19;
                                                 case 20: return sh20;
                                                 case 21: return sh21;
                                                 case 22: return sh22;
                                                 case 23: return sh23;
                                                 case 24: return sh24;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }

            set
            {
                switch (index)
                {
                                             case 0: sh0 = value; break;
                                                 case 1: sh1 = value; break;
                                                 case 2: sh2 = value; break;
                                                 case 3: sh3 = value; break;
                                                 case 4: sh4 = value; break;
                                                 case 5: sh5 = value; break;
                                                 case 6: sh6 = value; break;
                                                 case 7: sh7 = value; break;
                                                 case 8: sh8 = value; break;
                                                 case 9: sh9 = value; break;
                                                 case 10: sh10 = value; break;
                                                 case 11: sh11 = value; break;
                                                 case 12: sh12 = value; break;
                                                 case 13: sh13 = value; break;
                                                 case 14: sh14 = value; break;
                                                 case 15: sh15 = value; break;
                                                 case 16: sh16 = value; break;
                                                 case 17: sh17 = value; break;
                                                 case 18: sh18 = value; break;
                                                 case 19: sh19 = value; break;
                                                 case 20: sh20 = value; break;
                                                 case 21: sh21 = value; break;
                                                 case 22: sh22 = value; break;
                                                 case 23: sh23 = value; break;
                                                 case 24: sh24 = value; break;
                        
                    default:
                        throw new IndexOutOfRangeException();
                }
            }
        }

        [JsonIgnore]
        public bool IsValid =>
            Coder<T>.IsValid(sh0) &&
	Coder<T>.IsValid(sh1) &&
	Coder<T>.IsValid(sh2) &&
	Coder<T>.IsValid(sh3) &&
	Coder<T>.IsValid(sh4) &&
	Coder<T>.IsValid(sh5) &&
	Coder<T>.IsValid(sh6) &&
	Coder<T>.IsValid(sh7) &&
	Coder<T>.IsValid(sh8) &&
	Coder<T>.IsValid(sh9) &&
	Coder<T>.IsValid(sh10) &&
	Coder<T>.IsValid(sh11) &&
	Coder<T>.IsValid(sh12) &&
	Coder<T>.IsValid(sh13) &&
	Coder<T>.IsValid(sh14) &&
	Coder<T>.IsValid(sh15) &&
	Coder<T>.IsValid(sh16) &&
	Coder<T>.IsValid(sh17) &&
	Coder<T>.IsValid(sh18) &&
	Coder<T>.IsValid(sh19) &&
	Coder<T>.IsValid(sh20) &&
	Coder<T>.IsValid(sh21) &&
	Coder<T>.IsValid(sh22) &&
	Coder<T>.IsValid(sh23) &&
	Coder<T>.IsValid(sh24);

        public SphericalHarmonicsL4(T sh0, T sh1, T sh2, T sh3, T sh4, T sh5, T sh6, T sh7, T sh8, T sh9, T sh10, T sh11, T sh12, T sh13, T sh14, T sh15, T sh16, T sh17, T sh18, T sh19, T sh20, T sh21, T sh22, T sh23, T sh24)
        {
                            this.sh0 = sh0;
                                this.sh1 = sh1;
                                this.sh2 = sh2;
                                this.sh3 = sh3;
                                this.sh4 = sh4;
                                this.sh5 = sh5;
                                this.sh6 = sh6;
                                this.sh7 = sh7;
                                this.sh8 = sh8;
                                this.sh9 = sh9;
                                this.sh10 = sh10;
                                this.sh11 = sh11;
                                this.sh12 = sh12;
                                this.sh13 = sh13;
                                this.sh14 = sh14;
                                this.sh15 = sh15;
                                this.sh16 = sh16;
                                this.sh17 = sh17;
                                this.sh18 = sh18;
                                this.sh19 = sh19;
                                this.sh20 = sh20;
                                this.sh21 = sh21;
                                this.sh22 = sh22;
                                this.sh23 = sh23;
                                this.sh24 = sh24;
                        }

        public void Encode(BinaryWriter writer)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                Coder<T>.Encode(this[i], writer);
        }

        public DataTreeNode Save()
        {
            var coeffNames = new DataTreeList();

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                coeffNames.Add(Coder<T>.Save(this[i]));

            return coeffNames;
        }

        public void Load(DataTreeNode node)
        {
            var coeffNames = (DataTreeList)node;

            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Load(coeffNames[i]);
        }

        public void Decode(BinaryReader reader)
        {
            for (int i = 0; i < COEFFICIENT_COUNT; i++)
                this[i] = Coder<T>.Decode(reader);
        }

        public override string ToString() => this.FormatToString();

        public SphericalHarmonicsL4<O> Convert<O>(Func<T,O> conversion)
            where O : unmanaged, IEquatable<O>
        {
            return new SphericalHarmonicsL4<O>(
                conversion(sh0),
conversion(sh1),
conversion(sh2),
conversion(sh3),
conversion(sh4),
conversion(sh5),
conversion(sh6),
conversion(sh7),
conversion(sh8),
conversion(sh9),
conversion(sh10),
conversion(sh11),
conversion(sh12),
conversion(sh13),
conversion(sh14),
conversion(sh15),
conversion(sh16),
conversion(sh17),
conversion(sh18),
conversion(sh19),
conversion(sh20),
conversion(sh21),
conversion(sh22),
conversion(sh23),
conversion(sh24)
            );
        }

        #region INTERFACE OPERATIONS

        public SphericalHarmonicsL4<T> Add(SphericalHarmonicsL4<T> other) => this + other;
        public SphericalHarmonicsL4<T> Sub(SphericalHarmonicsL4<T> other) => this - other;
        public SphericalHarmonicsL4<T> Scale(float n) => this * n;
        public SphericalHarmonicsL4<T> LerpUnclamped(SphericalHarmonicsL4<T> other, float lerp) => MathX.LerpUnclamped(this, other, lerp);
        public SphericalHarmonicsL4<T> Lerp(SphericalHarmonicsL4<T> other, float lerp) => MathX.Lerp(this, other, lerp);
        public SphericalHarmonicsL4<T> ConstantLerp(SphericalHarmonicsL4<T> other, float delta) => MathX.ConstantLerp(this, other, delta);
        public SphericalHarmonicsL4<T> SmoothLerp(SphericalHarmonicsL4<T> other,
            ref SphericalHarmonicsL4<T> intermediate, float delta) => MathX.SmoothLerp(this, other, ref intermediate, delta);

        #endregion 

        #region OPERATORS

        public override bool Equals(object obj)
        {
            if (obj is SphericalHarmonicsL4<T> sh)
                return Equals(sh);

            return false;
        }

        public bool Equals(SphericalHarmonicsL4<T> other)
        {
            return sh0.Equals(other.sh0) && 
   sh1.Equals(other.sh1) && 
   sh2.Equals(other.sh2) && 
   sh3.Equals(other.sh3) && 
   sh4.Equals(other.sh4) && 
   sh5.Equals(other.sh5) && 
   sh6.Equals(other.sh6) && 
   sh7.Equals(other.sh7) && 
   sh8.Equals(other.sh8) && 
   sh9.Equals(other.sh9) && 
   sh10.Equals(other.sh10) && 
   sh11.Equals(other.sh11) && 
   sh12.Equals(other.sh12) && 
   sh13.Equals(other.sh13) && 
   sh14.Equals(other.sh14) && 
   sh15.Equals(other.sh15) && 
   sh16.Equals(other.sh16) && 
   sh17.Equals(other.sh17) && 
   sh18.Equals(other.sh18) && 
   sh19.Equals(other.sh19) && 
   sh20.Equals(other.sh20) && 
   sh21.Equals(other.sh21) && 
   sh22.Equals(other.sh22) && 
   sh23.Equals(other.sh23) && 
   sh24.Equals(other.sh24);
        }

        public override int GetHashCode()
        {
            int hashCode = 412434100;
                            hashCode = hashCode * -1521134295 + sh0.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh1.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh2.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh3.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh4.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh5.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh6.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh7.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh8.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh9.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh10.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh11.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh12.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh13.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh14.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh15.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh16.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh17.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh18.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh19.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh20.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh21.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh22.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh23.GetHashCode();
                                hashCode = hashCode * -1521134295 + sh24.GetHashCode();
                            return hashCode;
        }

        public static bool operator ==(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b)
            => a.Equals(b);

        public static bool operator !=(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b)
            => !a.Equals(b);

        public static SphericalHarmonicsL4<T> operator +(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b)
        {
            return new SphericalHarmonicsL4<T>
            (
                Coder<T>.Add(a.sh0, b.sh0),
Coder<T>.Add(a.sh1, b.sh1),
Coder<T>.Add(a.sh2, b.sh2),
Coder<T>.Add(a.sh3, b.sh3),
Coder<T>.Add(a.sh4, b.sh4),
Coder<T>.Add(a.sh5, b.sh5),
Coder<T>.Add(a.sh6, b.sh6),
Coder<T>.Add(a.sh7, b.sh7),
Coder<T>.Add(a.sh8, b.sh8),
Coder<T>.Add(a.sh9, b.sh9),
Coder<T>.Add(a.sh10, b.sh10),
Coder<T>.Add(a.sh11, b.sh11),
Coder<T>.Add(a.sh12, b.sh12),
Coder<T>.Add(a.sh13, b.sh13),
Coder<T>.Add(a.sh14, b.sh14),
Coder<T>.Add(a.sh15, b.sh15),
Coder<T>.Add(a.sh16, b.sh16),
Coder<T>.Add(a.sh17, b.sh17),
Coder<T>.Add(a.sh18, b.sh18),
Coder<T>.Add(a.sh19, b.sh19),
Coder<T>.Add(a.sh20, b.sh20),
Coder<T>.Add(a.sh21, b.sh21),
Coder<T>.Add(a.sh22, b.sh22),
Coder<T>.Add(a.sh23, b.sh23),
Coder<T>.Add(a.sh24, b.sh24)
            );
        }

        public static SphericalHarmonicsL4<T> operator -(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b)
        {
            return new SphericalHarmonicsL4<T>
            (
                Coder<T>.Sub(a.sh0, b.sh0),
Coder<T>.Sub(a.sh1, b.sh1),
Coder<T>.Sub(a.sh2, b.sh2),
Coder<T>.Sub(a.sh3, b.sh3),
Coder<T>.Sub(a.sh4, b.sh4),
Coder<T>.Sub(a.sh5, b.sh5),
Coder<T>.Sub(a.sh6, b.sh6),
Coder<T>.Sub(a.sh7, b.sh7),
Coder<T>.Sub(a.sh8, b.sh8),
Coder<T>.Sub(a.sh9, b.sh9),
Coder<T>.Sub(a.sh10, b.sh10),
Coder<T>.Sub(a.sh11, b.sh11),
Coder<T>.Sub(a.sh12, b.sh12),
Coder<T>.Sub(a.sh13, b.sh13),
Coder<T>.Sub(a.sh14, b.sh14),
Coder<T>.Sub(a.sh15, b.sh15),
Coder<T>.Sub(a.sh16, b.sh16),
Coder<T>.Sub(a.sh17, b.sh17),
Coder<T>.Sub(a.sh18, b.sh18),
Coder<T>.Sub(a.sh19, b.sh19),
Coder<T>.Sub(a.sh20, b.sh20),
Coder<T>.Sub(a.sh21, b.sh21),
Coder<T>.Sub(a.sh22, b.sh22),
Coder<T>.Sub(a.sh23, b.sh23),
Coder<T>.Sub(a.sh24, b.sh24)
            );
        }

        public static SphericalHarmonicsL4<T> operator *(SphericalHarmonicsL4<T> sh, float n)
        {
            return new SphericalHarmonicsL4<T>
            (
                Coder<T>.Scale(sh.sh0, n),
Coder<T>.Scale(sh.sh1, n),
Coder<T>.Scale(sh.sh2, n),
Coder<T>.Scale(sh.sh3, n),
Coder<T>.Scale(sh.sh4, n),
Coder<T>.Scale(sh.sh5, n),
Coder<T>.Scale(sh.sh6, n),
Coder<T>.Scale(sh.sh7, n),
Coder<T>.Scale(sh.sh8, n),
Coder<T>.Scale(sh.sh9, n),
Coder<T>.Scale(sh.sh10, n),
Coder<T>.Scale(sh.sh11, n),
Coder<T>.Scale(sh.sh12, n),
Coder<T>.Scale(sh.sh13, n),
Coder<T>.Scale(sh.sh14, n),
Coder<T>.Scale(sh.sh15, n),
Coder<T>.Scale(sh.sh16, n),
Coder<T>.Scale(sh.sh17, n),
Coder<T>.Scale(sh.sh18, n),
Coder<T>.Scale(sh.sh19, n),
Coder<T>.Scale(sh.sh20, n),
Coder<T>.Scale(sh.sh21, n),
Coder<T>.Scale(sh.sh22, n),
Coder<T>.Scale(sh.sh23, n),
Coder<T>.Scale(sh.sh24, n)
            );
        }

        public static SphericalHarmonicsL4<T> operator *(float n, SphericalHarmonicsL4<T> sh) => sh * n;

        public SphericalHarmonicsL4<T> ScaleOrders( float order0, float order1, float order2, float order3, float order4 )
        {
            return new SphericalHarmonicsL4<T>(
                Coder<T>.Scale(sh0, order0),
Coder<T>.Scale(sh1, order1),
Coder<T>.Scale(sh2, order1),
Coder<T>.Scale(sh3, order1),
Coder<T>.Scale(sh4, order2),
Coder<T>.Scale(sh5, order2),
Coder<T>.Scale(sh6, order2),
Coder<T>.Scale(sh7, order2),
Coder<T>.Scale(sh8, order2),
Coder<T>.Scale(sh9, order3),
Coder<T>.Scale(sh10, order3),
Coder<T>.Scale(sh11, order3),
Coder<T>.Scale(sh12, order3),
Coder<T>.Scale(sh13, order3),
Coder<T>.Scale(sh14, order3),
Coder<T>.Scale(sh15, order3),
Coder<T>.Scale(sh16, order4),
Coder<T>.Scale(sh17, order4),
Coder<T>.Scale(sh18, order4),
Coder<T>.Scale(sh19, order4),
Coder<T>.Scale(sh20, order4),
Coder<T>.Scale(sh21, order4),
Coder<T>.Scale(sh22, order4),
Coder<T>.Scale(sh23, order4),
Coder<T>.Scale(sh24, order4)
                );
        }

        #endregion
    }

    public static partial class MathX
    {
        public static SphericalHarmonicsL4<T> Lerp<T>(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            if(lerp <= 0f)
                return a;

            if(lerp >= 1f)
                return b;

            return LerpUnclamped(a, b, lerp);
        }

        public static SphericalHarmonicsL4<T> LerpUnclamped<T>(SphericalHarmonicsL4<T> a, SphericalHarmonicsL4<T> b, float lerp)
            where T : unmanaged, IEquatable<T>
        {
            return a + (b - a) * lerp;
        }

        public static SphericalHarmonicsL4<T> ConstantLerp<T>(SphericalHarmonicsL4<T> current, SphericalHarmonicsL4<T> target, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL4<T>(
                Coder<T>.ConstantLerp(current.sh0, target.sh0, delta),
Coder<T>.ConstantLerp(current.sh1, target.sh1, delta),
Coder<T>.ConstantLerp(current.sh2, target.sh2, delta),
Coder<T>.ConstantLerp(current.sh3, target.sh3, delta),
Coder<T>.ConstantLerp(current.sh4, target.sh4, delta),
Coder<T>.ConstantLerp(current.sh5, target.sh5, delta),
Coder<T>.ConstantLerp(current.sh6, target.sh6, delta),
Coder<T>.ConstantLerp(current.sh7, target.sh7, delta),
Coder<T>.ConstantLerp(current.sh8, target.sh8, delta),
Coder<T>.ConstantLerp(current.sh9, target.sh9, delta),
Coder<T>.ConstantLerp(current.sh10, target.sh10, delta),
Coder<T>.ConstantLerp(current.sh11, target.sh11, delta),
Coder<T>.ConstantLerp(current.sh12, target.sh12, delta),
Coder<T>.ConstantLerp(current.sh13, target.sh13, delta),
Coder<T>.ConstantLerp(current.sh14, target.sh14, delta),
Coder<T>.ConstantLerp(current.sh15, target.sh15, delta),
Coder<T>.ConstantLerp(current.sh16, target.sh16, delta),
Coder<T>.ConstantLerp(current.sh17, target.sh17, delta),
Coder<T>.ConstantLerp(current.sh18, target.sh18, delta),
Coder<T>.ConstantLerp(current.sh19, target.sh19, delta),
Coder<T>.ConstantLerp(current.sh20, target.sh20, delta),
Coder<T>.ConstantLerp(current.sh21, target.sh21, delta),
Coder<T>.ConstantLerp(current.sh22, target.sh22, delta),
Coder<T>.ConstantLerp(current.sh23, target.sh23, delta),
Coder<T>.ConstantLerp(current.sh24, target.sh24, delta));
        }

        public static SphericalHarmonicsL4<T> SmoothLerp<T>(SphericalHarmonicsL4<T> current,
            SphericalHarmonicsL4<T> target,
            ref SphericalHarmonicsL4<T> intermediate, float delta)
            where T : unmanaged, IEquatable<T>
        {
            return new SphericalHarmonicsL4<T>(
                Coder<T>.SmoothLerp(current.sh0, target.sh0, ref intermediate.sh0, delta),
Coder<T>.SmoothLerp(current.sh1, target.sh1, ref intermediate.sh1, delta),
Coder<T>.SmoothLerp(current.sh2, target.sh2, ref intermediate.sh2, delta),
Coder<T>.SmoothLerp(current.sh3, target.sh3, ref intermediate.sh3, delta),
Coder<T>.SmoothLerp(current.sh4, target.sh4, ref intermediate.sh4, delta),
Coder<T>.SmoothLerp(current.sh5, target.sh5, ref intermediate.sh5, delta),
Coder<T>.SmoothLerp(current.sh6, target.sh6, ref intermediate.sh6, delta),
Coder<T>.SmoothLerp(current.sh7, target.sh7, ref intermediate.sh7, delta),
Coder<T>.SmoothLerp(current.sh8, target.sh8, ref intermediate.sh8, delta),
Coder<T>.SmoothLerp(current.sh9, target.sh9, ref intermediate.sh9, delta),
Coder<T>.SmoothLerp(current.sh10, target.sh10, ref intermediate.sh10, delta),
Coder<T>.SmoothLerp(current.sh11, target.sh11, ref intermediate.sh11, delta),
Coder<T>.SmoothLerp(current.sh12, target.sh12, ref intermediate.sh12, delta),
Coder<T>.SmoothLerp(current.sh13, target.sh13, ref intermediate.sh13, delta),
Coder<T>.SmoothLerp(current.sh14, target.sh14, ref intermediate.sh14, delta),
Coder<T>.SmoothLerp(current.sh15, target.sh15, ref intermediate.sh15, delta),
Coder<T>.SmoothLerp(current.sh16, target.sh16, ref intermediate.sh16, delta),
Coder<T>.SmoothLerp(current.sh17, target.sh17, ref intermediate.sh17, delta),
Coder<T>.SmoothLerp(current.sh18, target.sh18, ref intermediate.sh18, delta),
Coder<T>.SmoothLerp(current.sh19, target.sh19, ref intermediate.sh19, delta),
Coder<T>.SmoothLerp(current.sh20, target.sh20, ref intermediate.sh20, delta),
Coder<T>.SmoothLerp(current.sh21, target.sh21, ref intermediate.sh21, delta),
Coder<T>.SmoothLerp(current.sh22, target.sh22, ref intermediate.sh22, delta),
Coder<T>.SmoothLerp(current.sh23, target.sh23, ref intermediate.sh23, delta),
Coder<T>.SmoothLerp(current.sh24, target.sh24, ref intermediate.sh24, delta));
        }
    }
    